//! **The single source of truth for the Lisp files this build generates.**
//!
//! GNU does not ship `lisp/international/charscript.el` or
//! `lisp/international/emoji-zwj.el`.  It *builds* them, and
//! `admin/unidata/Makefile.in:110-123` is the whole recipe:
//!
//! ```make
//! # Don't use $^, since that includes the awk script.
//! ${unidir}/charscript.el: ${blocks_sources}
//!     $(AM_V_GEN)$(AWK) -f ${blocks} ${blocks_sources} > $@
//!
//! ${unidir}/emoji-zwj.el: ${zwj_sources}
//!     $(AM_V_GEN)$(AWK) -f ${zwj} ${zwj_sources} > $@
//! ```
//!
//! One rule per file, no post-processing: **what awk prints is the file.**
//!
//! # Why this file exists
//!
//! Until ledger 206 this port had two producers for those two names:
//!
//! * `cargo xtask fresh-build` ran GNU's awk, as above.
//! * `neovm-core/build.rs` ran `build_support/unicode_gen.rs`, a hand-written
//!   Rust reimplementation of both awk scripts, over a second byte-identical
//!   copy of GNU's Unicode data in `crates/neovm-core/unicode-data/`.
//!
//! Whichever ran last decided the bytes, and they disagreed.  Two costs:
//!
//! 1. `write_if_changed` rewrote `emoji-zwj.el` on every profile switch, which
//!    left `emoji-zwj.elc` older than its source -- so the first debug build
//!    after a release build made the tree stale, by construction, every time.
//!    Ledger 203 §7.4.
//! 2. The reimplementation double-escaped the `\U0001F1E6`-style character
//!    escapes in the two hand-derived flag blocks, so the shipped image's
//!    `composition-function-table` held a 23-character literal where GNU holds
//!    the five-character regexp `[🇦-🇿]`.  Country flags and UK subdivision
//!    flags did not compose.  Ledger 206.
//!
//! Porting the awk more carefully was never the answer.  The project's
//! standing directive is not to reimplement what GNU already ships, and here
//! it cannot even be done: GNU's `for (elt in ch)` walks an awk associative
//! array, so its 150 emoji entries come out in gawk's internal hash order,
//! which no other language reproduces.
//!
//! # How to keep it one producer
//!
//! Every consumer includes THIS FILE and iterates
//! [`AWK_GENERATED_UNICODE_LISP`]; nobody writes those paths any other way:
//!
//! * `neovm-core/build.rs` -- `#[path = "build_support/generated_lisp.rs"]`
//! * `crates/xtask/src/main.rs` -- `#[path = "../../neovm-core/build_support/generated_lisp.rs"]`
//! * `crates/neovm-core/src/emacs_core/tests/build_support/generated_lisp.rs`, which runs the recipe
//!   and diffs the bytes on disk, so a third producer fails there by name
//!   whatever crate it lives in.
//!
//! This is the same arrangement as `jit/shim_names.rs`, which
//! `neovm-core/build.rs` and `crates/neomacs/build.rs` both `include!` so their
//! export sets cannot drift.
//!
//! Ledger 206.

#![allow(dead_code)]

use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// GNU's `$(AWK)`.  `configure` refuses a tree without one, and so does this.
pub const AWK_PROGRAM: &str = "awk";

/// GNU's equivalent command, shown in logs; decoding runs portably in Rust.
pub const GUNZIP_PROGRAM: &str = "gunzip";

/// GNU's directory of Unicode inputs and the awk scripts that read them.
///
/// There is one copy.  `crates/neovm-core/unicode-data/` was a second, and it existed
/// only to feed the reimplementation this file replaced.
pub const GNU_UNIDATA_DIR: &str = "admin/unidata";

/// Where GNU's Makefile puts the results (`${unidir}`).
pub const GENERATED_LISP_DIR: &str = "lisp";

/// One Lisp file this build generates by running one of GNU's own awk scripts.
///
/// Every field is a path GNU already has.  There is deliberately no field for
/// "produced some other way": a row cannot describe a Rust reimplementation,
/// because the only thing a row can name is a script and its inputs.
pub struct AwkGeneratedLisp {
    /// The generated file, relative to [`GENERATED_LISP_DIR`].
    pub output: &'static str,
    /// GNU's awk script, relative to [`GNU_UNIDATA_DIR`].
    pub script: &'static str,
    /// GNU's data files, relative to [`GNU_UNIDATA_DIR`], in GNU's own order.
    /// The order is observable: awk reads them as one concatenated stream.
    pub inputs: &'static [&'static str],
    /// The line in GNU's Makefile this row transcribes, so a reader can check
    /// it rather than trust it.
    pub gnu_rule: &'static str,
}

/// Every awk-generated Lisp file, in GNU's Makefile order.
///
/// `admin/unidata/Makefile.in` has exactly these two awk rules; the rest of
/// that Makefile's targets are generated by `unidata-gen.el` running inside a
/// bootstrap Emacs, which `xtask` drives separately because it needs a built
/// binary and a build script cannot have one.
pub const AWK_GENERATED_UNICODE_LISP: &[AwkGeneratedLisp] = &[
    AwkGeneratedLisp {
        output: "international/charscript.el",
        script: "blocks.awk",
        inputs: &["Blocks.txt", "emoji-data.txt"],
        gnu_rule: "admin/unidata/Makefile.in:111-112",
    },
    AwkGeneratedLisp {
        output: "international/emoji-zwj.el",
        script: "emoji-zwj.awk",
        inputs: &["emoji-zwj-sequences.txt", "emoji-sequences.txt"],
        gnu_rule: "admin/unidata/Makefile.in:122-123",
    },
];

/// GNU's directory of charset translation awk scripts (`${srcdir}` in
/// `admin/charsets/Makefile.in`).
pub const GNU_CHARSETS_DIR: &str = "admin/charsets";

/// GNU's `${charsetdir}`: the (committed) charset map data those scripts read.
pub const ETC_CHARSETS_DIR: &str = "etc/charsets";

/// Where a charset recipe's awk script reads its data.
///
/// The unidata rules hand awk their inputs as command-line arguments; GNU's
/// charset rules redirect a file into awk's **stdin**, and one of them
/// gunzips first (`admin/charsets/Makefile.in:213-217`).  A row cannot express
/// one as the other, so the difference is part of the row.
#[derive(Clone, Copy, Debug)]
pub enum CharsetInput {
    /// `${charsetdir}/<name>`, redirected into awk's stdin (`< $<`).
    Map { name: &'static str },
    /// `${GLIBC_CHARMAPS}/<name>` (under `admin/charsets/glibc/`), gunzipped
    /// into awk's stdin (`gunzip -c $< | $(AWK) …`).
    GzippedGlibcCharmap { name: &'static str },
}

/// One charset-translation Lisp file this build generates by running one of
/// GNU's own `admin/charsets` awk scripts.  Same doctrine as
/// [`AwkGeneratedLisp`]: every field is a path GNU already has, and there is
/// no field for "produced some other way".
pub struct CharsetTranslationLisp {
    /// The generated file, relative to `lisp/` (`${lispintdir}`).
    pub output: &'static str,
    /// GNU's awk script, relative to [`GNU_CHARSETS_DIR`].
    pub script: &'static str,
    /// Where awk's stdin comes from.
    pub input: CharsetInput,
    /// The line in GNU's Makefile this row transcribes.
    pub gnu_rule: &'static str,
}

/// The charset-translation recipes, in GNU's Makefile order.
///
/// These two files are why a checkout with no build output cannot bootstrap:
/// `lisp/loadup.el` loads both with **no** noerror flag
/// (`(load "international/cp51932")`, `(load "international/eucjp-ms")`,
/// loadup.el:231-232), so a tree that lacks them fails `loadup` -- and with it
/// every daemon-lifecycle test, whose fixture dumps its runtime image from
/// exactly that loadup.  They are generated here, in the build, so that a
/// fresh `cargo build` produces a bootable tree the way GNU's `make` does.
pub const AWK_GENERATED_CHARSET_LISP: &[CharsetTranslationLisp] = &[
    CharsetTranslationLisp {
        output: "international/cp51932.el",
        script: "cp51932.awk",
        input: CharsetInput::Map {
            name: "CP932-2BYTE.map",
        },
        gnu_rule: "admin/charsets/Makefile.in:213-214",
    },
    CharsetTranslationLisp {
        output: "international/eucjp-ms.el",
        script: "eucjp-ms.awk",
        input: CharsetInput::GzippedGlibcCharmap {
            name: "EUC-JP-MS.gz",
        },
        gnu_rule: "admin/charsets/Makefile.in:216-217",
    },
];

/// The trees a recipe touches, named rather than implied.
///
/// They are not always the same repository: `cargo xtask fresh-build` reads
/// GNU's scripts and data from the checkout (`repo_root/admin/unidata`) but
/// writes into whatever runtime tree it was pointed at
/// (`runtime_root/lisp`), which is how it builds an installed image.  A
/// recipe that took one root would silently write into the wrong one.
#[derive(Clone, Debug)]
pub struct GeneratedLispRoots {
    /// GNU's `admin/unidata`: the awk scripts and the Unicode data.
    pub unidata_dir: PathBuf,
    /// GNU's `admin/charsets`: `cp51932.awk`, `eucjp-ms.awk`, `glibc/`.
    pub charsets_dir: PathBuf,
    /// GNU's `${charsetdir}`: the committed charset map data.
    pub etc_charsets_dir: PathBuf,
    /// The `lisp/` tree the outputs belong in.
    pub lisp_root: PathBuf,
}

impl GeneratedLispRoots {
    /// The ordinary case: every tree is this checkout.
    pub fn of_project(project_root: &Path) -> Self {
        Self {
            unidata_dir: project_root.join(GNU_UNIDATA_DIR),
            charsets_dir: project_root.join(GNU_CHARSETS_DIR),
            etc_charsets_dir: project_root.join(ETC_CHARSETS_DIR),
            lisp_root: project_root.join(GENERATED_LISP_DIR),
        }
    }
}

/// What [`AwkGeneratedLisp::regenerate`] did.
///
/// `Unchanged` is the common case and the load-bearing one: leaving the mtime
/// alone is what stops a rebuild from invalidating the `.elc` beside it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Regenerated {
    /// The bytes on disk already matched; nothing was written and no mtime
    /// moved.
    Unchanged,
    /// The file did not exist or held different bytes, and was rewritten.
    Written,
}

impl AwkGeneratedLisp {
    /// The generated file's absolute path.
    pub fn output_path(&self, roots: &GeneratedLispRoots) -> PathBuf {
        roots.lisp_root.join(self.output)
    }

    /// GNU's awk script's absolute path.
    pub fn script_path(&self, roots: &GeneratedLispRoots) -> PathBuf {
        roots.unidata_dir.join(self.script)
    }

    /// GNU's data files, in GNU's order.
    pub fn input_paths(&self, roots: &GeneratedLispRoots) -> Vec<PathBuf> {
        self.inputs
            .iter()
            .map(|name| roots.unidata_dir.join(name))
            .collect()
    }

    /// Every file the recipe reads: the script first, then its inputs.
    ///
    /// This is what a build system watches, and GNU watches the same set --
    /// `${unidir}/emoji-zwj.el` is declared to depend on `${zwj}` and on
    /// `${zwj_sources}` in two separate rules for exactly that reason.
    pub fn dependencies(&self, roots: &GeneratedLispRoots) -> Vec<PathBuf> {
        let mut deps = vec![self.script_path(roots)];
        deps.extend(self.input_paths(roots));
        deps
    }

    /// The command line this recipe runs, for a build log or a `--dry-run`.
    pub fn command_line(&self, roots: &GeneratedLispRoots) -> String {
        let mut line = format!("{AWK_PROGRAM} -f {}", self.script_path(roots).display());
        for input in self.input_paths(roots) {
            line.push(' ');
            line.push_str(&input.display().to_string());
        }
        format!("{line} > {}", self.output_path(roots).display())
    }

    /// Run GNU's awk and return exactly the bytes it printed.
    ///
    /// Nothing is written, and nothing is normalised: the caller compares or
    /// stores the bytes as they came out, because GNU's Makefile redirects
    /// awk's stdout straight into the file.
    pub fn generate(&self, roots: &GeneratedLispRoots) -> Result<Vec<u8>, String> {
        let script = self.script_path(roots);
        let inputs = self.input_paths(roots);
        for path in std::iter::once(&script).chain(inputs.iter()) {
            if !path.is_file() {
                return Err(format!(
                    "missing generator input {} (GNU {})",
                    path.display(),
                    self.gnu_rule
                ));
            }
        }

        let output = Command::new(AWK_PROGRAM)
            .arg("-f")
            .arg(&script)
            .args(&inputs)
            .output()
            .map_err(|err| {
                format!(
                    "could not run `{AWK_PROGRAM}` for {}: {err}.  GNU's build \
                     requires awk too ({}); install one (gawk) and rebuild",
                    self.output, self.gnu_rule,
                )
            })?;
        if !output.status.success() {
            return Err(format!(
                "`{AWK_PROGRAM} -f {}` exited {}: {}",
                script.display(),
                output.status,
                String::from_utf8_lossy(&output.stderr).trim(),
            ));
        }
        if output.stdout.is_empty() {
            return Err(format!(
                "`{AWK_PROGRAM} -f {}` printed nothing; {} would be empty",
                script.display(),
                self.output,
            ));
        }
        Ok(output.stdout)
    }

    /// Generate, and write only if the bytes differ.
    ///
    /// The "only if" is the whole point.  A build script that rewrote an
    /// identical file would move its mtime past the `.elc` compiled from it,
    /// and ledger 202's refusal would -- correctly -- stop every in-process
    /// test in the tree.
    pub fn regenerate(&self, roots: &GeneratedLispRoots) -> Result<Regenerated, String> {
        let generated = self.generate(roots)?;
        let output = self.output_path(roots);
        if std::fs::read(&output).is_ok_and(|current| current == generated) {
            return Ok(Regenerated::Unchanged);
        }
        if let Some(parent) = output.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|err| format!("create {}: {err}", parent.display()))?;
        }
        std::fs::write(&output, &generated)
            .map_err(|err| format!("write {}: {err}", output.display()))?;
        Ok(Regenerated::Written)
    }
}

impl CharsetTranslationLisp {
    /// The generated file's absolute path.
    pub fn output_path(&self, roots: &GeneratedLispRoots) -> PathBuf {
        roots.lisp_root.join(self.output)
    }

    /// GNU's awk script's absolute path.
    pub fn script_path(&self, roots: &GeneratedLispRoots) -> PathBuf {
        roots.charsets_dir.join(self.script)
    }

    /// The file awk's stdin comes from.
    pub fn input_path(&self, roots: &GeneratedLispRoots) -> PathBuf {
        match self.input {
            CharsetInput::Map { name } => roots.etc_charsets_dir.join(name),
            CharsetInput::GzippedGlibcCharmap { name } => {
                roots.charsets_dir.join("glibc").join(name)
            }
        }
    }

    /// Every file the recipe reads: the script first, then its input.
    pub fn dependencies(&self, roots: &GeneratedLispRoots) -> Vec<PathBuf> {
        vec![self.script_path(roots), self.input_path(roots)]
    }

    /// The equivalent GNU command line, for a build log or a `--dry-run`.
    pub fn command_line(&self, roots: &GeneratedLispRoots) -> String {
        let source = match self.input {
            CharsetInput::Map { .. } => format!("< {}", self.input_path(roots).display()),
            CharsetInput::GzippedGlibcCharmap { .. } => {
                format!("{GUNZIP_PROGRAM} -c {} |", self.input_path(roots).display())
            }
        };
        format!(
            "{source} {AWK_PROGRAM} -f {} > {}",
            self.script_path(roots).display(),
            self.output_path(roots).display()
        )
    }

    /// Return GNU awk's unmodified output, using GNU's script and input bytes.
    ///
    /// Decode gzip in Rust because Git for Windows ships gunzip as a shell
    /// script, which a native process cannot spawn directly. All gzip members
    /// and their checksums are validated before awk runs; decoding changes only
    /// the transport, leaving GNU's awk as the sole Lisp generator.
    pub fn generate(&self, roots: &GeneratedLispRoots) -> Result<Vec<u8>, String> {
        let script = self.script_path(roots);
        let input = self.input_path(roots);
        for path in [&script, &input] {
            if !path.is_file() {
                return Err(format!(
                    "missing generator input {} (GNU {})",
                    path.display(),
                    self.gnu_rule
                ));
            }
        }

        let mut command = Command::new(AWK_PROGRAM);
        command
            .arg("-f")
            .arg(&script)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        let file = std::fs::File::open(&input)
            .map_err(|err| format!("open {}: {err}", input.display()))?;
        let decompressed = match self.input {
            CharsetInput::Map { .. } => {
                command.stdin(Stdio::from(file));
                None
            }
            CharsetInput::GzippedGlibcCharmap { .. } => {
                let mut bytes = Vec::new();
                flate2::read::MultiGzDecoder::new(file)
                    .read_to_end(&mut bytes)
                    .map_err(|err| format!("decode gzip {}: {err}", input.display()))?;
                command.stdin(Stdio::piped());
                Some(bytes)
            }
        };
        let mut child = command.spawn().map_err(|err| {
            format!(
                "could not run `{AWK_PROGRAM}` for {}: {err}.  GNU's build \
                 requires awk too ({}); install one (gawk) and rebuild",
                self.output, self.gnu_rule,
            )
        })?;
        // Feed stdin concurrently with draining stdout: GNU's charset output
        // exceeds pipe capacity, so writing first could deadlock both sides.
        let writer = decompressed.map(|bytes| {
            let mut stdin = child.stdin.take().expect("piped awk stdin");
            std::thread::spawn(move || stdin.write_all(&bytes))
        });
        let output = child.wait_with_output();
        let written = writer.map(|writer| writer.join());
        let output = output.map_err(|err| format!("waiting for {AWK_PROGRAM}: {err}"))?;
        // Report awk's failure before any consequential broken stdin pipe.
        if !output.status.success() {
            return Err(format!(
                "`{AWK_PROGRAM} -f {}` exited {}: {}",
                script.display(),
                output.status,
                String::from_utf8_lossy(&output.stderr).trim(),
            ));
        }
        if let Some(written) = written {
            written
                .map_err(|_| format!("feeding {} to awk: writer panicked", input.display()))?
                .map_err(|err| format!("feeding {} to awk: {err}", input.display()))?;
        }
        if output.stdout.is_empty() {
            return Err(format!(
                "`{AWK_PROGRAM} -f {}` printed nothing; {} would be empty",
                script.display(),
                self.output,
            ));
        }
        Ok(output.stdout)
    }

    /// Generate, and write only if the bytes differ ([`AwkGeneratedLisp::regenerate`]).
    pub fn regenerate(&self, roots: &GeneratedLispRoots) -> Result<Regenerated, String> {
        let generated = self.generate(roots)?;
        let output = self.output_path(roots);
        if std::fs::read(&output).is_ok_and(|current| current == generated) {
            return Ok(Regenerated::Unchanged);
        }
        if let Some(parent) = output.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|err| format!("create {}: {err}", parent.display()))?;
        }
        std::fs::write(&output, &generated)
            .map_err(|err| format!("write {}: {err}", output.display()))?;
        Ok(Regenerated::Written)
    }
}
