//! Types for the Rust layout engine.
//!
//! These are the intermediate representation between buffer data and rendering.
//! The layout engine produces display rows and frame display state snapshots
//! that renderers consume without owning display semantics.

use neomacs_display_protocol::cursor::CursorBarWidth;
use neomacs_display_protocol::types::Rect;
use neovm_core::emacs_core::image_catalog::{
    ImageCatalog, ImageLookup, ImageResolveRequest, ImageScaleEnvironment, ImageSizeLimit,
};

/// Numeric extent of a mini-window walk, owned by one exclusive attempt.
/// Full measurement is only requested before GNU window-change hooks. It
/// carries no Lisp values, shared cache, renderer or presentation authority.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum MiniWindowMeasurement {
    #[default]
    Presentation,
    ToEnd,
}

/// Parameters for a window that the layout engine needs.
/// Populated from Emacs data via FFI before layout runs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct LayoutCharPos0(i64);

impl LayoutCharPos0 {
    pub const fn new(value: i64) -> Self {
        Self(value)
    }

    pub const fn get(self) -> i64 {
        self.0
    }
}

/// The first buffer position regenerated by an incremental body walk.
///
/// This is deliberately not a semantic window position such as point or
/// window-start.  A partial walk may begin far from point while still needing
/// the real point to derive row decoration such as
/// `line-number-current-line`.  Keeping the roles distinct prevents replay
/// code from suppressing viewport adjustment by counterfeiting semantic state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct PartialBodyWalkStart(LayoutCharPos0);

impl PartialBodyWalkStart {
    pub const fn new(value: i64) -> Self {
        Self(LayoutCharPos0::new(value))
    }

    pub const fn get(self) -> i64 {
        self.0.get()
    }
}

/// How the layout engine should handle text that exceeds the right edge.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum LineWrapMode {
    /// Lines that exceed the window width are truncated with a continuation
    /// glyph (e.g. `$`).
    #[default]
    Truncate,
    /// Lines that exceed the window width wrap to the next visual row.
    Wrap,
}

/// Complete GNU display policy for non-ASCII spaces and hyphens.
///
/// GNU keeps `nobreak-char-display` and `nobreak-char-ascii-display` as
/// separate Lisp/C variables, but redisplay consumes their product as one of
/// these four behaviors.  Keeping that product closed prevents callers from
/// losing the distinction between highlighting the original character and
/// replacing it with its ASCII lookalike.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum NobreakDisplayMode {
    #[default]
    Literal,
    HighlightOriginal,
    HighlightAscii,
    Escape,
}

impl NobreakDisplayMode {
    pub(crate) const fn highlights(self) -> bool {
        matches!(self, Self::HighlightOriginal | Self::HighlightAscii)
    }
}

/// GNU `display-line-numbers` modes understood by the layout engine.
///
/// This is a closed semantic domain rather than the old `u8` transport code:
/// adding a mode now requires every renderer and retained-layout policy to
/// handle it explicitly.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum DisplayLineNumbersMode {
    #[default]
    Off,
    Absolute,
    Relative,
    Visual,
}

/// How bare point motion can change pixels baked into retained body rows.
///
/// Cursor decoration itself is replayed separately. This dependency describes
/// point-derived *body* content which cannot be repaired by moving only the
/// cursor.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PointMotionBodyDependency {
    /// No retained body glyph depends on point.
    Independent,
    /// Only decoration of the display row containing point can change.
    CurrentDisplayRow,
    /// Point contributes to values throughout the visible window.
    EntireWindow,
}

impl DisplayLineNumbersMode {
    pub const fn enabled(self) -> bool {
        !matches!(self, Self::Off)
    }

    /// Apply GNU's window-kind gate before line-number geometry enters layout.
    ///
    /// `maybe_produce_line_number` rejects minibuffer windows outright.  Keep
    /// that invariant in the typed snapshot so downstream row planning cannot
    /// reserve or paint a line-number gutter for a minibuffer.
    pub const fn for_window_kind(self, kind: WindowKind) -> Self {
        match kind {
            WindowKind::Main => self,
            WindowKind::Minibuffer => Self::Off,
        }
    }

    /// GNU `xdisp.c` point-motion invalidation expressed as layout data.
    pub const fn point_motion_body_dependency(self) -> PointMotionBodyDependency {
        match self {
            Self::Off => PointMotionBodyDependency::Independent,
            Self::Absolute => PointMotionBodyDependency::CurrentDisplayRow,
            Self::Relative | Self::Visual => PointMotionBodyDependency::EntireWindow,
        }
    }
}

/// Semantic category of a window within its frame.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum WindowKind {
    /// A normal editing window.
    #[default]
    Main,
    /// The minibuffer window.
    Minibuffer,
}

impl WindowKind {
    pub const fn is_minibuffer(self) -> bool {
        matches!(self, Self::Minibuffer)
    }
}

/// Shared handle to the host's image catalog, carried into layout so a
/// `(space :align-to (… (image …)))` operand can be resolved to real pixels —
/// GNU does this inline with `lookup_image` (xdisp.c:30506).
///
/// A handle rather than a borrow: layout's pixel arithmetic stays free of any
/// lifetime tied to the display host. `None` on frames without a catalog,
/// which reproduces GNU's `FRAME_WINDOW_P` guard (the operand, and with it the
/// whole expression, simply fails).
#[derive(Clone)]
pub struct SharedImageCatalog(pub std::rc::Rc<dyn ImageCatalog>);

impl std::fmt::Debug for SharedImageCatalog {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SharedImageCatalog(..)")
    }
}

impl WindowParams {
    /// Inputs for resolving `(image …)` operands inside `(space …)` specs.
    pub(crate) fn space_image_inputs(&self) -> crate::display_pixel_calc::PixelCalcImageInputs {
        crate::display_pixel_calc::PixelCalcImageInputs {
            catalog: self.space_image_catalog.clone(),
            scale: self.image_scale_environment,
            dimensions: crate::display_spec::DisplayImageDimensionEnvironment::new(
                self.font_pixel_size,
                self.char_height,
                self.char_width,
            ),
            default_fg: self.default_fg,
            default_bg: self.default_bg,
        }
    }
}

impl SharedImageCatalog {
    /// `limit` is the looking frame's resolved `max-image-size`; it travels
    /// with the request rather than being read here, because the layout engine
    /// holds no obarray.
    #[must_use]
    pub fn lookup(&self, request: ImageResolveRequest, limit: ImageSizeLimit) -> ImageLookup {
        self.0.lookup(request, limit)
    }
}

/// Whether this window owns the frame's one active physical cursor.
///
/// This is deliberately independent of Lisp window selection and active
/// mode-line styling.  GNU can redirect the active cursor to an inactive
/// echo-area mini-window without selecting that window.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WindowCursorRole {
    Active,
    Inactive,
}

impl WindowCursorRole {
    pub const fn from_active(active: bool) -> Self {
        if active { Self::Active } else { Self::Inactive }
    }

    pub const fn is_active(self) -> bool {
        matches!(self, Self::Active)
    }
}

#[derive(Debug, Clone)]
pub struct WindowParams {
    /// Window identifier (pointer value)
    pub window_id: i64,
    /// Buffer identifier (pointer value)
    pub buffer_id: u64,
    /// Frame-absolute bounds
    pub bounds: Rect,
    /// Text area bounds (excludes fringes, margins, scroll bars)
    pub text_bounds: Rect,
    /// Whether this is the selected window
    pub selected: bool,
    /// Whether this window owns the frame's active physical cursor.
    pub cursor_role: WindowCursorRole,
    /// Whether this window's mode/header-line chrome uses the active face.
    /// During an active minibuffer this remains true for the window that
    /// invoked the minibuffer even though the minibuffer owns input/cursor
    /// selection.
    pub mode_line_active: bool,
    /// What kind of window this is (main editing area or minibuffer).
    pub kind: WindowKind,
    /// Independent character-grid origin; never derived from pixel bounds.
    pub left_col: i64,
    pub top_line: i64,

    /// First visible buffer position in layout 0-based char coordinates.
    /// Derived from GNU `marker_position (w->start)`.
    pub window_start: i64,
    /// A stack-local measurement is bounded by rows, not viewport pixels.
    /// Redisplay leaves this absent and uses the physical window extent.
    pub measurement_rows: Option<std::num::NonZeroUsize>,
    /// GNU mini preparation walks all display rows through accessible EOB.
    pub mini_measurement: MiniWindowMeasurement,
    /// Explicit pixel extent for a synchronous query, independent of the viewport.
    pub measurement_pixels: Option<std::num::NonZeroUsize>,
    /// Complete a live viewport query once its target row has been emitted.
    pub query_target: Option<LayoutCharPos0>,
    /// GNU `w->force_start`: `window_start` was set explicitly (scroll /
    /// set-window-start), so layout must display from it and move POINT into
    /// the window when point ended up outside — never recompute the start
    /// around point.
    pub force_start: bool,
    /// Buffer position just AFTER the last character the previous redisplay
    /// actually displayed, in layout 0-based char coordinates — GNU's
    /// `BUF_Z (b) - w->window_end_pos`.  Positions strictly before this
    /// exclusive end were visible.  Equality normally denotes the first
    /// position below the span, except at accessible EOB: the EOB cursor sits
    /// on that insertion boundary and can still be visible on the final row.
    /// Callers must defer that boundary case to current-layout cursor-row
    /// measurement.
    ///
    /// `None` when GNU's `window_end_valid` is clear, i.e. the buffer or the
    /// window changed since that layout and the position describes nothing.
    ///
    /// This is the only display-accurate fact available before laying out:
    /// unlike a count of buffer lines it already accounts for wrapped lines and
    /// for text the display hides.
    pub previous_visible_end: Option<i64>,
    /// Point position in this window's buffer in layout 0-based char coordinates.
    pub point: i64,
    /// Accessible end (ZV) in layout 0-based exclusive char coordinates.
    pub buffer_size: i64,
    /// The displayed buffer's `MODIFF` at layout time.
    pub buffer_modiff: i64,
    /// Accessible start (BEGV) in layout 0-based char coordinates.
    pub buffer_begv: i64,

    /// Effective typed `display-line-numbers` mode for this layout snapshot.
    pub display_line_numbers: DisplayLineNumbersMode,

    /// Horizontal scroll offset in columns
    pub hscroll: i32,
    /// Vertical scroll offset in pixels (shifts content up)
    pub vscroll: i32,

    /// How to handle long lines.
    pub wrap_mode: LineWrapMode,
    /// Whether to wrap at word boundaries
    pub word_wrap: bool,
    /// Tab width in columns
    pub tab_width: i32,
    /// Custom tab stop positions (column numbers), from tab-stop-list buffer-local.
    /// Empty means use fixed-width tab_width stops only.
    pub tab_stop_list: Vec<i32>,

    /// `scroll-conservatively` (buffer-local with global fallback). When point
    /// jumps more than this many lines off-screen, redisplay RECENTERS point to
    /// the window middle instead of scrolling minimally (GNU `try_scrolling`
    /// SCROLLING_FAILED → the `recenter:` label, src/xdisp.c:19360/21108). A
    /// value above 100 (GNU `SCROLL_LIMIT`) disables recentering entirely.
    pub scroll_conservatively: i64,
    /// `scroll-step`: how many lines to scroll when point moves off-screen and
    /// `scroll-conservatively` is 0 (GNU `emacs_scroll_step`, consumed by
    /// `try_scrolling` as `amount_to_scroll = scroll_max`, src/xdisp.c:19497).
    pub scroll_step: i64,
    /// `scroll-minibuffer-conservatively` (GNU default t, bug#44070): a
    /// mini-window scrolls minimally whatever `scroll-conservatively` says
    /// (GNU passes `SCROLL_LIMIT + 1` for it, src/xdisp.c:21083).
    pub scroll_minibuffer_conservatively: bool,
    /// `scroll-margin`: minimum lines of context kept between point and the top
    /// or bottom window edge on a minimal scroll (GNU `window_scroll_margin`).
    pub scroll_margin: i64,

    /// Default face foreground/background for this window
    pub default_fg: u32,
    pub default_bg: u32,

    /// Character cell dimensions
    pub char_width: f32,
    pub char_height: f32,
    /// Whether the containing frame is a real window-system frame.
    pub window_system: bool,
    /// Font pixel size
    pub font_pixel_size: f32,
    /// Immutable GNU image-scaling facts inherited from the containing frame.
    pub image_scale_environment: ImageScaleEnvironment,

    /// Shared image catalog used to resolve `(image …)` operands inside
    /// `(space :width/:align-to …)` expressions before layout arithmetic runs.
    /// `None` on frames without a catalog — GNU's `FRAME_WINDOW_P` guard.
    pub space_image_catalog: Option<SharedImageCatalog>,
    /// Font ascent
    pub font_ascent: f32,

    /// Mode-line height (0 if no mode-line)
    pub mode_line_height: f32,
    /// Header-line height (0 if no header-line)
    pub header_line_height: f32,
    /// Tab-line height (0 if no tab-line)
    pub tab_line_height: f32,

    /// Cursor kind for this window. The discriminant matches GNU's
    /// `enum text_cursor_kinds` exactly (`FilledBox=0`, `HollowBox=1`,
    /// `Bar=2`, `Hbar=3`, `NoCursor=-1`, `Default=-2`). Cursor audit
    /// Finding 1 in `drafts/cursor-audit.md` flagged the previous
    /// `u8` encoding as a silently re-numbered alias.
    pub cursor_kind: neomacs_display_protocol::frame_glyphs::CursorKind,
    /// Cursor bar width (for bar cursor)
    pub cursor_bar_width: CursorBarWidth,
    /// Whether stretch slots may use their full displayed width for box cursors.
    ///
    /// Mirrors GNU `x-stretch-cursor`.
    pub x_stretch_cursor: bool,
    /// Cursor color in sRGB pixel format.
    pub cursor_color: u32,
    /// Foreground used to redraw a glyph inside a filled cursor when the
    /// glyph face alone cannot provide a contrasting color. Mirrors GNU's
    /// per-frame `cursor_foreground_pixel` / `cursor_foreground_color`.
    pub cursor_foreground: u32,
    /// Neomacs-specific cursor effect profile for this window.
    pub cursor_effects: Option<neomacs_display_protocol::effect_config::EffectsConfig>,
    /// Neomacs-only visual cursors for this window's buffer.
    ///
    /// These do not affect GNU point, mark, selection, command dispatch, or
    /// IME state. They are render-only cursor visuals anchored to buffer
    /// positions.
    pub visual_cursors: Vec<VisualCursorSpec>,

    /// Fringe widths in pixels
    pub left_fringe_width: f32,
    pub right_fringe_width: f32,
    /// Whether fringes are outside margins in the horizontal band ordering.
    pub fringes_outside_margins: bool,
    /// indicate-empty-lines: 0=off, 1=left, 2=right
    pub indicate_empty_lines: i32,
    /// Whether to show trailing whitespace
    pub show_trailing_whitespace: bool,
    /// Trailing-whitespace face background color
    pub trailing_ws_bg: u32,
    /// Fill-column-indicator column (-1 = off, nonnegative = column)
    pub fill_column_indicator: i32,
    /// Fill-column-indicator character
    pub fill_column_indicator_char: char,
    /// Fill-column-indicator face foreground color
    pub fill_column_indicator_fg: u32,
    /// Extra line spacing in pixels
    pub extra_line_spacing: f32,
    /// selective-display: 0=off, >0=hide lines indented more than N columns
    pub selective_display: i32,
    /// escape-glyph face foreground color
    pub escape_glyph_fg: u32,
    /// Effective `nobreak-char-display` + `nobreak-char-ascii-display` policy.
    pub nobreak_char_display: NobreakDisplayMode,
    /// nobreak-char face foreground color
    pub nobreak_char_fg: u32,
    /// glyphless-char face foreground color
    pub glyphless_char_fg: u32,
    /// wrap-prefix: bytes rendered at start of continuation lines
    pub wrap_prefix: Vec<u8>,
    /// line-prefix: bytes rendered at start of all visual lines
    pub line_prefix: Vec<u8>,
    /// Left margin width in pixels (0 = no margin)
    pub left_margin_width: f32,
    /// Left margin width in character columns.
    pub left_margin_columns: i64,
    /// Right margin width in pixels (0 = no margin)
    pub right_margin_width: f32,
    /// Right margin width in character columns.
    pub right_margin_columns: i64,

    // --- Scroll bar configuration ---
    /// Effective vertical scroll bar side for this window.
    /// `None` when disabled, `Some("left")` or `Some("right")` when enabled.
    pub vertical_scroll_bar_side: Option<String>,
    /// Whether a horizontal scroll bar is shown below the text area.
    pub horizontal_scroll_bar: bool,
    /// Vertical scroll bar track width in pixels (0 when disabled).
    pub scroll_bar_pixel_width: f32,
    /// Horizontal scroll bar track height in pixels (0 when disabled).
    pub scroll_bar_pixel_height: f32,
}

impl WindowParams {
    pub const fn is_minibuffer(&self) -> bool {
        self.kind.is_minibuffer()
    }

    /// Initial source-interpretation coverage for this walk. Fontification,
    /// conditional display and composition must all honor offscreen queries;
    /// the physical viewport is only the default for a presentation walk.
    pub(crate) fn source_interpretation_rows(&self) -> usize {
        if self.mini_measurement == MiniWindowMeasurement::ToEnd {
            return usize::MAX;
        }
        self.measurement_rows.map_or_else(
            || {
                (self
                    .measurement_pixels
                    .map_or(self.text_bounds.height, |height| height.get() as f32)
                    / self.char_height.max(1.0))
                .ceil()
                .max(1.0) as usize
            },
            std::num::NonZeroUsize::get,
        )
    }

    pub fn window_start_charpos(&self) -> LayoutCharPos0 {
        LayoutCharPos0::new(self.window_start)
    }

    pub fn previous_visible_end_charpos(&self) -> Option<LayoutCharPos0> {
        self.previous_visible_end.map(LayoutCharPos0::new)
    }

    pub fn point_charpos(&self) -> LayoutCharPos0 {
        LayoutCharPos0::new(self.point)
    }

    pub fn accessible_start_charpos(&self) -> LayoutCharPos0 {
        LayoutCharPos0::new(self.buffer_begv)
    }

    pub fn accessible_end_charpos(&self) -> LayoutCharPos0 {
        LayoutCharPos0::new(self.buffer_size)
    }
}

#[derive(Clone, Debug)]
pub struct VisualCursorSpec {
    pub id: i32,
    /// 0-based buffer character position.
    pub charpos: i64,
    pub cursor_kind: neomacs_display_protocol::frame_glyphs::CursorKind,
    pub cursor_bar_width: CursorBarWidth,
    pub color: u32,
    pub effects: Option<neomacs_display_protocol::effect_config::EffectsConfig>,
}

/// Frame-level parameters for layout.
#[derive(Debug, Clone)]
pub struct FrameParams {
    /// Frame pixel dimensions
    pub width: f32,
    pub height: f32,
    /// Frame-level menu-bar height in pixels.
    ///
    /// Mirrors GNU `FRAME_MENU_BAR_HEIGHT (f)`. On TTY frames this is
    /// `menu-bar-lines * char_height` (with `char_height = 1`); the
    /// layout engine reserves this many pixels at the top of the frame
    /// for the menu bar row, mirroring `display_menu_bar()` in xdisp.c.
    pub menu_bar_height: f32,
    /// Frame-level tool-bar height in pixels.
    pub tool_bar_height: f32,
    /// Frame-level compact-bar height in pixels.
    pub compact_bar_height: f32,
    /// Frame-level tab-bar height in pixels.
    pub tab_bar_height: f32,
    /// Default character cell dimensions
    pub char_width: f32,
    pub char_height: f32,
    /// Font pixel size
    pub font_pixel_size: f32,
    /// Immutable GNU image-scaling facts for this frame attempt.
    pub image_scale_environment: ImageScaleEnvironment,
    /// Whether this frame is backed by a window-system display.
    pub window_system: bool,
    /// Frame background color (sRGB pixel)
    pub background: u32,
    /// Vertical border face foreground color (sRGB pixel)
    pub vertical_border_fg: u32,
    /// Window edge that owns zero-width internal vertical borders.
    ///
    /// This follows the frame parameter consumed by GNU `mouse-drag-line`,
    /// rather than any individual window's effective scroll-bar override, so
    /// every shared boundary has exactly one owner.
    pub zero_width_vertical_border_edge: neomacs_display_protocol::PresentedResizeEdge,
    /// Right window divider width in pixels (0 = disabled)
    pub right_divider_width: i32,
    /// Bottom window divider width in pixels (0 = disabled)
    pub bottom_divider_width: i32,
    /// Window-divider face foreground color (sRGB pixel)
    pub divider_fg: u32,
    /// Window-divider-first-pixel face foreground color (sRGB pixel)
    pub divider_first_fg: u32,
    /// Window-divider-last-pixel face foreground color (sRGB pixel)
    pub divider_last_fg: u32,
}

#[cfg(test)]
#[path = "types/tests/types_test.rs"]
mod tests;
