;;; neomacs-mcp-responsive-tests.el --- Admission and read regressions -*- lexical-binding: t; -*-

;; Source definitions only until the scheduling hold is explicitly released.
(require 'ert)
(require 'cl-lib)
(require 'neomacs-mcp)
(require 'neomacs-mcp-editor)

(defun neomacs-mcp-test--request (peer id &optional generation)
  "Return a production-enqueued request for PEER, ID and GENERATION."
  (let ((neomacs-mcp--queue nil)
        (neomacs-mcp--generation (or generation neomacs-mcp--generation)))
    ;; Use the real constructor: cancellation mutates its existing plist slot.
    ;; A hand-built plist without that slot loses updates through shared aliases.
    (cl-letf (((symbol-function 'neomacs-mcp--schedule) #'ignore))
      (neomacs-mcp--enqueue
       peer (neomacs-mcp--object "id" id "method" "fixture")))
    (car neomacs-mcp--queue)))

(ert-deftest neomacs-mcp-responsive-input-defers-and-recovers ()
  (let* ((neomacs-mcp--active nil) (neomacs-mcp--timer nil)
         (neomacs-mcp--queue (list (neomacs-mcp-test--request 'a 1)
                                   (neomacs-mcp-test--request 'b 2)))
         (pending t) (calls nil) (scheduled 0))
    (cl-letf (((symbol-function 'input-pending-p)
               (lambda (&rest args)
                 (should (equal args '(nil)))
                 ;; Exercise the guard with injected reentry at the polling boundary.
                 (neomacs-mcp--drain)
                 pending))
              ((symbol-function 'neomacs-mcp--live-p) (lambda (&rest _) t))
              ((symbol-function 'neomacs-mcp--dispatch)
               (lambda (peer _) (push peer calls) (neomacs-mcp--object)))
              ((symbol-function 'neomacs-mcp--send) #'ignore)
              ((symbol-function 'neomacs-mcp--schedule) (lambda () (cl-incf scheduled))))
      (neomacs-mcp--drain)
      (should-not calls)
      (should (= 2 (length neomacs-mcp--queue)))
      (should-not neomacs-mcp--active)
      (setq pending nil)
      (neomacs-mcp--drain)
      (should (equal calls '(a)))
      (should (= 1 (length neomacs-mcp--queue)))
      (neomacs-mcp--drain)
      (should (equal calls '(b a)))
      (should-not neomacs-mcp--queue)
      (should (= scheduled 3)))))

(ert-deftest neomacs-mcp-responsive-bounded-retirement ()
  (let* ((neomacs-mcp--active nil) (neomacs-mcp--timer nil)
         (neomacs-mcp--queue
          (append (cl-loop repeat (1+ neomacs-mcp--scan-limit)
                           collect (list :peer 'a :cancelled t))
                  (list (neomacs-mcp-test--request 'b 1))))
         (calls 0))
    (cl-letf (((symbol-function 'input-pending-p) (lambda (&optional _) nil))
              ((symbol-function 'neomacs-mcp--live-p) (lambda (&rest _) t))
              ((symbol-function 'neomacs-mcp--schedule) #'ignore)
              ((symbol-function 'neomacs-mcp--send) #'ignore)
              ((symbol-function 'neomacs-mcp--dispatch)
               (lambda (&rest _) (cl-incf calls) (neomacs-mcp--object))))
      (neomacs-mcp--drain)
      (should (= calls 0))
      (should (= 2 (length neomacs-mcp--queue)))
      (neomacs-mcp--drain)
      (should (= calls 1))
      (should-not neomacs-mcp--queue))))

(ert-deftest neomacs-mcp-responsive-control-cancel-and-generation ()
  (let* ((neomacs-mcp--active nil) (neomacs-mcp--timer nil)
         (neomacs-mcp--generation 7) (neomacs-mcp--peers '(a b))
         (neomacs-mcp--queue (list (neomacs-mcp-test--request 'a 1)
                                   (neomacs-mcp-test--request 'a 2 6)
                                   (neomacs-mcp-test--request 'dead 3)
                                   (neomacs-mcp-test--request 'b 1)))
         (calls nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'input-pending-p)
               (lambda (&optional _)
                 (neomacs-mcp--frame 'a "{\"jsonrpc\":\"2.0\",\"method\":\"notifications/cancelled\",\"params\":{\"requestId\":1}}")
                 nil))
              ((symbol-function 'neomacs-mcp--schedule) #'ignore)
              ((symbol-function 'neomacs-mcp--send) #'ignore)
              ((symbol-function 'neomacs-mcp--dispatch)
               (lambda (peer _) (push peer calls) (neomacs-mcp--object))))
      (neomacs-mcp--drain)
      (should (equal calls '(b)))
      (should-not neomacs-mcp--queue))))

(ert-deftest neomacs-mcp-responsive-unwind-and-abandoned-send ()
  (dolist (exit '(error quit throw cancel))
    (let* ((neomacs-mcp--active nil) (neomacs-mcp--timer nil)
           (request (neomacs-mcp-test--request 'a 1))
           (neomacs-mcp--queue (list request (neomacs-mcp-test--request 'b 2)))
           (sent 0) (scheduled 0))
      (cl-letf (((symbol-function 'input-pending-p) (lambda (&optional _) nil))
                ((symbol-function 'neomacs-mcp--live-p) (lambda (&rest _) t))
                ((symbol-function 'neomacs-mcp--schedule) (lambda () (cl-incf scheduled)))
                ((symbol-function 'process-send-string) (lambda (&rest _) (cl-incf sent)))
                ((symbol-function 'run-at-time) (lambda (&rest _) 'timer))
                ((symbol-function 'cancel-timer) #'ignore)
                ((symbol-function 'process-put) #'ignore)
                ((symbol-function 'process-get) (lambda (&rest _) nil))
                ((symbol-function 'neomacs-mcp--dispatch)
                 (lambda (&rest _)
                   (pcase exit
                     ('error (error "Fixture"))
                     ('quit (signal 'quit nil))
                     ('throw (throw 'fixture t))
                     ('cancel (neomacs-mcp--cancel 'a 1) (neomacs-mcp--object))))))
        (catch 'fixture (neomacs-mcp--drain))
        (should-not neomacs-mcp--active)
        (should (= scheduled 1))
        (should (= 1 (length neomacs-mcp--queue)))
        (should (= sent (if (memq exit '(throw cancel)) 0 1)))))))

(defun neomacs-mcp-test--editor-args (&rest pairs)
  "Return editor arguments containing the current instance and PAIRS."
  (apply #'neomacs-mcp--object
         "instance" (gethash "instance" (neomacs-mcp-identity)) pairs))

(ert-deftest neomacs-mcp-editor-optional-registration ()
  (let ((neomacs-mcp-tools (copy-tree neomacs-mcp-tools))
        (neomacs-mcp--listener nil) (before (buffer-list)))
    (neomacs-mcp-enable-editor-tools)
    (neomacs-mcp-enable-editor-tools)
    (should (= 1 (cl-count "neomacs_buffer_read" neomacs-mcp-tools :key #'car :test #'equal)))
    (should (assoc "neomacs_eval" neomacs-mcp-tools))
    (should (equal before (buffer-list)))
    (should-not neomacs-mcp--listener)))

(ert-deftest neomacs-mcp-editor-literal-range-and-protected-state ()
  (let* ((study (current-buffer)) (window (selected-window))
         (window-buffer (window-buffer window)) (window-point (window-point window))
         (window-start (window-start window))
         (buffer (generate-new-buffer "mcp-read-fixture")))
    (unwind-protect
        (with-current-buffer buffer
          (insert (propertize "α\n\"\\β終🙂text" 'face 'bold))
          (buffer-enable-undo)
          (goto-char 5) (set-mark 6) (setq mark-active t)
          (narrow-to-region 3 9)
          (let* ((point (point)) (mark (mark)) (minimum (point-min)) (maximum (point-max))
                 (undo buffer-undo-list) (tick (buffer-modified-tick))
                 (args (neomacs-mcp-test--editor-args "name" (buffer-name) "start" 1
                                                       "maxChars" 5 "expectedTick" tick))
                 (value (neomacs-mcp--buffer-read args)))
            (should (equal (gethash "text" value) "α\n\"\\β"))
            (should-not (text-properties-at 0 (gethash "text" value)))
            (should (= (gethash "start" value) 1))
            (should (= (gethash "end" value) 6))
            (should (= (gethash "nextStart" value) 6))
            (should (eq (gethash "truncated" value) t))
            (should (= (gethash "tick" value) tick))
            (should (eq (current-buffer) buffer))
            (should (= point (point))) (should (= mark (mark)))
            (should mark-active)
            (should (= minimum (point-min))) (should (= maximum (point-max)))
            (should (eq undo buffer-undo-list))
            (should (= tick (buffer-modified-tick)))))
      (kill-buffer buffer))
    (should (eq (current-buffer) study))
    (should (eq (selected-window) window))
    (should (eq (window-buffer window) window-buffer))
    (should (= (window-point window) window-point))
    (should (= (window-start window) window-start))))

(ert-deftest neomacs-mcp-editor-validation-tick-and-eob ()
  (with-temp-buffer
    (rename-buffer "mcp-validation-fixture" t)
    (insert "abc")
    (let ((args (neomacs-mcp-test--editor-args "name" (buffer-name) "start" 1 "maxChars" 4)))
      (dolist (pair '(("instance" . "wrong") ("name" . "absent-mcp-fixture")
                      ("start" . 0) ("start" . 5) ("maxChars" . 0)
                      ("maxChars" . 4097) ("expectedTick" . -1)))
        (let ((bad (copy-hash-table args)))
          (puthash (car pair) (cdr pair) bad)
          (should-error (neomacs-mcp--buffer-read bad))))
      (puthash "expectedTick" (buffer-modified-tick) args)
      (insert "d")
      (should-error (neomacs-mcp--buffer-read args))
      (remhash "expectedTick" args)
      (puthash "start" (point-max) args)
      (let ((value (neomacs-mcp--buffer-read args)))
        (should (equal "" (gethash "text" value)))
        (should (eq :false (gethash "truncated" value)))
        (should (eq :null (gethash "nextStart" value)))))))

(ert-deftest neomacs-mcp-editor-encoded-budget-and-distant-start ()
  (with-temp-buffer
    (rename-buffer "mcp-output-fixture" t)
    (insert (make-string 100000 ?x) (make-string 4096 1) "🙂")
    (let* ((neomacs-mcp-editor-output-limit 2048)
           (value (neomacs-mcp--buffer-read
                   (neomacs-mcp-test--editor-args "name" (buffer-name) "start" 100001 "maxChars" 4096)))
           (text (gethash "text" value)))
      (should (> (length text) 0))
      (should (< (length text) 4096))
      (should (<= (neomacs-mcp--editor-result-bytes value) neomacs-mcp-editor-output-limit))
      (should (= (gethash "end" value) (+ 100001 (length text))))
      (should (eq t (gethash "truncated" value)))
      (should (equal text (make-string (length text) 1))))))

(ert-deftest neomacs-mcp-editor-discovery-bounded-native-slots ()
  (let* ((buffers (cl-loop for n below 40 collect (generate-new-buffer (format "mcp-list-%s" n))))
         (current (current-buffer)))
    (unwind-protect
        (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) buffers)))
          (let* ((value (neomacs-mcp--buffer-list
                         (neomacs-mcp-test--editor-args "offset" 0 "limit" 2)))
                 (entries (gethash "buffers" value)))
            (should (= 2 (length entries)))
            (should (= 2 (gethash "nextOffset" value)))
            (should (eq t (gethash "truncated" value)))
            (should (equal (gethash "name" (aref entries 0)) (buffer-name (car buffers))))
            (should (<= (neomacs-mcp--editor-result-bytes value) neomacs-mcp-editor-output-limit))
            (should (eq current (current-buffer))))
          (dolist (pair '(("offset" . -1) ("limit" . 0) ("limit" . 33)))
            (should-error (neomacs-mcp--buffer-list
                           (neomacs-mcp-test--editor-args "offset" (if (equal (car pair) "offset") (cdr pair) 0)
                                                         "limit" (if (equal (car pair) "limit") (cdr pair) 1)))))
          (should-error (neomacs-mcp--buffer-list (neomacs-mcp--object "instance" "wrong" "offset" 0 "limit" 1))))
      (mapc #'kill-buffer buffers))))

(ert-deftest neomacs-mcp-editor-no-minibuffer-or-credential-disclosure ()
  (let* ((secret (generate-new-buffer "mcp-secret-fixture"))
         (alias (make-indirect-buffer secret "mcp-secret-alias" nil)))
    (unwind-protect
        (progn
          (with-current-buffer secret (setq buffer-file-name "/fixture/.authinfo.gpg"))
          (dolist (buffer (list secret alias (window-buffer (minibuffer-window))))
            (should (neomacs-mcp--editor-denied-p buffer))
            (should-error (neomacs-mcp--buffer-read
                           (neomacs-mcp-test--editor-args "name" (buffer-name buffer) "start" 1 "maxChars" 1))))
          (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (make-list 200 secret))))
            (let ((value (neomacs-mcp--buffer-list (neomacs-mcp-test--editor-args "offset" 0 "limit" 1))))
              (should (= 0 (length (gethash "buffers" value))))
              (should (= neomacs-mcp-editor-scan-limit (gethash "scanned" value)))
              (should (= neomacs-mcp-editor-scan-limit (gethash "nextOffset" value))))))
      (kill-buffer alias) (kill-buffer secret))))

(ert-deftest neomacs-mcp-responsive-native-pending-and-regular-reschedule ()
  (let* ((neomacs-mcp--active nil) (neomacs-mcp--timer nil)
         (neomacs-mcp--queue (list (neomacs-mcp-test--request 'a 1)))
         (unread-command-events '(?x)) (calls 0) (timers nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest args) (push args timers) 'fixture-timer))
              ((symbol-function 'neomacs-mcp--live-p) (lambda (&rest _) t))
              ((symbol-function 'neomacs-mcp--send) #'ignore)
              ((symbol-function 'neomacs-mcp--dispatch)
               (lambda (&rest _) (cl-incf calls) (neomacs-mcp--object))))
      ;; Use the real input predicate, not a timer-running replacement.
      (neomacs-mcp--drain)
      (should (= calls 0))
      (should (equal unread-command-events '(?x)))
      (should (equal timers '((0.01 nil neomacs-mcp--drain))))
      (setq unread-command-events nil neomacs-mcp--timer nil)
      (neomacs-mcp--drain)
      (should (= calls 1))
      (should-not neomacs-mcp--queue))))

(ert-deftest neomacs-mcp-editor-current-namesake-not-enduring-identity ()
  (let* ((old (generate-new-buffer "mcp-namesake"))
         (name (buffer-name old)) (replacement nil))
    (unwind-protect
        (progn
          (with-current-buffer old (insert "old") (rename-buffer "mcp-renamed" t))
          (setq replacement (get-buffer-create name))
          (with-current-buffer replacement (insert "new"))
          (let ((value (neomacs-mcp--buffer-read
                        (neomacs-mcp-test--editor-args "name" name "start" 1 "maxChars" 3))))
            (should (equal "new" (gethash "text" value)))
            (should (= (gethash "tick" value)
                       (with-current-buffer replacement (buffer-modified-tick))))))
      (when replacement (kill-buffer replacement)) (kill-buffer old))))

(ert-deftest neomacs-mcp-editor-no-expensive-read-paths-and-outer-budget ()
  (let ((buffer (generate-new-buffer "mcp-no-hooks"))
        (neomacs-mcp-tools (copy-tree neomacs-mcp-tools)) (forbidden nil))
    (unwind-protect
        (progn
          (with-current-buffer buffer (insert "Ελλάδα\n"))
          (neomacs-mcp-enable-editor-tools)
          (cl-letf (((symbol-function 'line-number-at-pos) (lambda (&rest _) (push 'lines forbidden) 0))
                    ((symbol-function 'find-file) (lambda (&rest _) (push 'files forbidden)))
                    ((symbol-function 'project-current) (lambda (&rest _) (push 'project forbidden)))
                    ((symbol-function 'font-lock-ensure) (lambda (&rest _) (push 'fontify forbidden))))
            (let* ((result (neomacs-mcp--call
                            (neomacs-mcp--object
                             "name" "neomacs_buffer_read" "arguments"
                             (neomacs-mcp-test--editor-args "name" (buffer-name buffer) "start" 1 "maxChars" 4096)) t))
                   (wire (json-serialize result :false-object :false :null-object :null)))
              (should (eq :false (gethash "isError" result)))
              (should (<= (string-bytes wire) neomacs-mcp-editor-output-limit))))
          ;; Assert outside production error handlers; mocks must not swallow failures.
          (should-not forbidden))
      (kill-buffer buffer))))

(provide 'neomacs-mcp-responsive-tests)
;;; neomacs-mcp-responsive-tests.el ends here
