;;; clients.el --- Strict server.el/native client acceptance -*- lexical-binding: t; -*-
;; The vendored GNU Lisp owns server frame selection and client lifetime.
(defvar native-proof-client-hooks nil)
(add-hook 'server-after-make-frame-hook
          (lambda ()
            (push (list (frame-parameter nil 'name) (selected-frame)
                        (frame-parameter nil 'client)) native-proof-client-hooks)))
(defun native-proof-frame (name)
  (cl-find-if (lambda (frame) (equal (frame-parameter frame 'name) name)) (frame-list)))
(defun native-proof-check-client (name nowait)
  (let ((frame (native-proof-frame name)))
    (unless frame (error "Client returned without a real graphical frame: %s" name))
    (select-frame frame)
    (redisplay t)
    (native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
    (let* ((client (frame-parameter frame 'client))
           (hook (cl-find-if (lambda (row) (equal (car row) name)) native-proof-client-hooks)))
      (unless (and (eq (framep frame) 'neo) hook (eq (cadr hook) frame)
                   (eq (caddr hook) client)
                   (if nowait (eq client 'nowait)
                     (and (processp client) (process-live-p client))))
        (error "Wrong server selection/hook/client ownership: %S %S" frame hook)))))
(defun native-proof-two-owned-frames (name)
  (setq native-proof-owned-first (native-proof-frame name)
        native-proof-owned-client (frame-parameter native-proof-owned-first 'client))
  (let ((selected (selected-frame)))
    (setq native-proof-owned-second
          (make-frame `((window-system . neo) (display . "wayland-ewm-proof")
                        (client . ,native-proof-owned-client) (name . "second-owned"))))
    (unless (eq selected (selected-frame)) (error "Plain make-frame changed selection")))
  (select-frame native-proof-owned-second)
  (redisplay t)
  (native-proof-wait (lambda () (= (native-proof-mapped-count) 2)))
  (delete-frame native-proof-owned-first t)
  (native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
  (unless (and (not (frame-live-p native-proof-owned-first))
               (frame-live-p native-proof-owned-second)
               (process-live-p native-proof-owned-client)
               (eq (frame-parameter native-proof-owned-second 'client) native-proof-owned-client))
    (error "First deletion disconnected an independently owned live second frame")))
(defvar native-proof-buffer-completions nil)
(defun native-proof-complete-buffer (name command)
  (let* ((frame (native-proof-frame name))
         (client (frame-parameter frame 'client))
         (buffers (process-get client 'buffers))
         (buffer (car buffers))
         (initial (cl-find-if #'frame-initial-p (frame-list)))
         (done-count 0)
         (done-hook (lambda () (setq done-count (1+ done-count)))))
    (unless (and initial (process-live-p client) (= (length buffers) 1)
                 (eq (frame-terminal frame) native-proof-terminal)
                 (equal (with-current-buffer buffer server-buffer-clients) (list client)))
      (error "Wrong waiting buffer ownership before completion: %S" name))
    ;; Select the initial frame before GNU server Lisp deletes the last GUI
    ;; frame, then classifies its still-owned terminal.
    (select-frame initial)
    (unwind-protect
        (with-current-buffer buffer
          (add-hook 'server-done-hook done-hook nil t)
          (pcase command
            ('server-buffer-done (server-buffer-done buffer))
            ('server-edit (server-edit))
            (_ (error "Unexpected completion command: %S" command))))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer (remove-hook 'server-done-hook done-hook t))))
    (unless (and (= done-count 1) (not (process-live-p client))
                 (not (memq client server-clients))
                 (null (process-get client 'buffers))
                 (not (frame-live-p frame))
                 (eq (terminal-live-p native-proof-terminal) 'neo)
                 (memq native-proof-terminal (terminal-list))
                 (= native-proof-pid (emacs-pid))
                 (or (not (buffer-live-p buffer))
                     (with-current-buffer buffer (null server-buffer-clients))))
      (error "Ordinary last-buffer completion leaked or duplicated ownership: %S" name))
    (native-proof-retained-state)
    (push (list name command done-count) native-proof-buffer-completions)))
(defun native-proof-final ()
  (garbage-collect)
  (native-proof-retained-state)
  (unless (and (= native-proof-pid (emacs-pid)) (eq native-proof-sentinel native-proof-alias)
               (equal native-proof-counts '(1 2 1 0 1))
               (not (frame-live-p native-proof-first))
               (not (frame-live-p native-proof-second))
               (equal (with-current-buffer native-proof-buffer (buffer-string)) "before native attachment")
               (equal (ewm-hello) "Hello from EWM compositor!") (daemonp))
    (error "Final persistent evaluator/module/native assertions failed"))
  (setq native-proof-final-frame
        (make-frame '((window-system . neo) (display . "wayland-ewm-proof") (name . "final-recreated"))))
  (select-frame native-proof-final-frame)
  (redisplay t)
  (native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
  (native-proof-retained-state)
  (with-temp-file (getenv "PROOF_OUTPUT")
    (prin1 `((strict_native_and_gnu_clients . t)
             (native_mapped_counts . ,native-proof-counts)
             (pid . ,(emacs-pid)) (module_hello . ,(ewm-hello))
             (buffer_completions . ,native-proof-buffer-completions)
             (client_hooks . ,native-proof-client-hooks)
             (native_state . ,(native-proof-retained-state))) (current-buffer))))
