
(defun native-proof-retained-state ()
  (let* ((state (ewm-get-debug-state-module))
         (holders (alist-get 'keyboard_capture_holders state)))
    (unless (and (= (alist-get 'emacs_pid state) native-proof-pid) (alist-get 'debug_mode state)
                 (cl-find-if (lambda (holder) (equal (cadr holder) "native-retained-state")) holders))
      (error "Native debug/capture state lost: %S" state))
    state))
(native-proof-retained-state)
;; The native display owner survives last-frame deletion, but cannot yet
;; retire/reconnect its terminal independently. Explicit deletion is atomic.
(defun native-proof-reject-terminal-deletion ()
  (let ((before (frame-list))
        (hook-ran nil)
        (delete-terminal-functions (list (lambda (_terminal) (setq hook-ran t))))
        (delete-frame-functions (list (lambda (_frame) (setq hook-ran t)))))
    (unless (condition-case error
                (progn (delete-terminal native-proof-terminal t) nil)
              (error
               (equal (cadr error) "Deleting a retained graphical display terminal is not supported")))
      (let ((frame (x-create-frame '((display . "wayland-ewm-proof")))))
        (error "Explicit terminal deletion admitted live-frame=%S dead-terminal=%S"
               (frame-live-p frame) (not (terminal-live-p (frame-terminal frame))))))
    (unless (and (not hook-ran) (equal before (frame-list))
                 (terminal-live-p native-proof-terminal)
                 (memq native-proof-terminal (terminal-list)))
      (error "Rejected terminal deletion mutated frames, hooks or terminal ownership"))))
(garbage-collect)
(native-proof-retained-state)
;; Failed explicit socket open must not publish a frame or consume winit's
;; successful singleton; this happens after real compositor readiness.
(setq native-proof-frames-before (frame-list))
(setq native-proof-create-hooks nil)
(defun native-proof-created (frame) (push frame native-proof-create-hooks))
(add-hook 'after-make-frame-functions #'native-proof-created)
(unless (condition-case nil
            (progn (make-frame '((window-system . neo) (display . "missing-native-socket"))) nil)
          (error t))
  (error "Bad explicit display unexpectedly opened"))
(unless (equal native-proof-frames-before (frame-list)) (error "Phantom frame on failed open"))
(when native-proof-create-hooks (error "Frame creation hook ran on failed open"))
;; Connection-only updates before first native frame exceed capacity64.
(x-open-connection "wayland-ewm-proof")
(dotimes (_ 256) (neomacs--effect-set 'window-resize :enabled t))

(setq native-proof-first (make-frame '((window-system . neo) (display . "wayland-ewm-proof") (name . "native-first") (width . 70) (height . 20))))
(unless (eq (car native-proof-create-hooks) native-proof-first) (error "Successful creation hook missing"))
(select-frame-set-input-focus native-proof-first)
(set-window-buffer (frame-selected-window native-proof-first) native-proof-buffer)
(redisplay t)
(native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
(native-proof-wait
 (lambda ()
   (cl-find-if (lambda (event)
                 (and (consp event) (eq (car event) 'new)
                      (= (or (alist-get 'pid (cdr event)) -1) native-proof-pid)))
               native-proof-events)))
(setq native-proof-counts (append native-proof-counts (list (native-proof-mapped-count))))
(setq native-proof-terminal (frame-terminal native-proof-first))
(setq native-proof-second (make-frame '((window-system . neo) (display . "wayland-ewm-proof") (name . "native-second") (width . 50) (height . 15))))
(select-frame-set-input-focus native-proof-second)
(redisplay t)
(native-proof-wait (lambda () (= (native-proof-mapped-count) 2)))
(native-proof-reject-terminal-deletion)
(setq native-proof-counts (append native-proof-counts (list (native-proof-mapped-count))))
(delete-frame native-proof-first t)
(native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
(setq native-proof-counts (append native-proof-counts (list (native-proof-mapped-count))))
(delete-frame native-proof-second t)
(native-proof-wait (lambda () (= (native-proof-mapped-count) 0)))
(native-proof-reject-terminal-deletion)
(setq native-proof-counts (append native-proof-counts (list (native-proof-mapped-count))))
(garbage-collect)
(native-proof-retained-state)
(unless (and (= native-proof-pid (emacs-pid)) (eq native-proof-sentinel native-proof-alias)
             (equal (with-current-buffer native-proof-buffer (buffer-string)) "before native attachment")
             (equal (ewm-hello) "Hello from EWM compositor!") (daemonp))
  (error "Evaluator/module state lost after last native frame close"))
(setq native-proof-third (make-frame '((window-system . neo) (display . "wayland-ewm-proof") (name . "native-recreated") (width . 60) (height . 18))))
(unless (and (eq (frame-terminal native-proof-third) native-proof-terminal)
             (terminal-live-p (frame-terminal native-proof-third)))
  (error "Recreated frame does not own the retained live terminal"))
(select-frame-set-input-focus native-proof-third)
(set-window-buffer (frame-selected-window native-proof-third) native-proof-buffer)
(redisplay t)
(native-proof-wait (lambda () (= (native-proof-mapped-count) 1)))
(setq native-proof-counts (append native-proof-counts (list (native-proof-mapped-count))))
(with-temp-file (getenv "PROOF_OUTPUT")
  (prin1 `((strict_core_native_journey . t) (full_434_closure . nil) (future_native_display_predeclared . nil)
           (native_mapped_counts . ,native-proof-counts)
           (pid_before . ,native-proof-pid) (pid_after . ,(emacs-pid))
           (lisp_identity . ,(eq native-proof-sentinel native-proof-alias))
           (preserved_buffer . ,(with-current-buffer native-proof-buffer (buffer-string)))
           (module_hello . ,(ewm-hello)) (native_token . ,native-proof-token)
           (first_dead . ,(not (frame-live-p native-proof-first)))
           (second_dead . ,(not (frame-live-p native-proof-second)))
           (recreated_live . ,(frame-live-p native-proof-third))
           (explicit_terminal_deletion_rejected . t)
           (display_list . ,(x-display-list))
           (native_state_before . ,native-proof-native-before)
           (native_state . ,(native-proof-retained-state))) (current-buffer)))
