(require 'cl-lib)
(defvar native-proof-events nil)
(defun native-proof-filter (_process _bytes)
  (setq native-proof-events (append native-proof-events (ewm-drain-events))))
(defun native-proof-wait (predicate)
  (let ((deadline (+ (float-time) 20)))
    (while (and (< (float-time) deadline) (not (funcall predicate)))
      (accept-process-output nil 0.05))
    (unless (funcall predicate) (error "Native EWM proof deadline expired"))))
(defvar native-proof-counts nil)
(defun native-proof-mapped-count ()
  (cl-count-if (lambda (surface) (and (alist-get 'mapped surface) (not (alist-get 'unmapped_set surface))))
               (alist-get 'acceptance_native_surfaces (ewm-get-debug-state-module))))
(setq native-proof-pid (emacs-pid)
      native-proof-sentinel (list 'same-evaluator (make-symbol "identity"))
      native-proof-alias native-proof-sentinel
      native-proof-buffer (get-buffer-create "*native-proof-preserved*"))
(with-current-buffer native-proof-buffer (insert "before native attachment"))
(unless (and (daemonp) (null (getenv "DISPLAY"))
             (null (getenv "WAYLAND_DISPLAY"))
             (null (getenv "WAYLAND_SOCKET"))
             (not (file-exists-p (expand-file-name "wayland-ewm-proof" (getenv "XDG_RUNTIME_DIR")))))
  (error "Private future socket must not exist at daemon readiness"))
(module-load (getenv "PROOF_MODULE"))
(unless (equal (ewm-hello) "Hello from EWM compositor!") (error "Actual EWM module missing"))
(ewm-debug-mode-module t)
(setq native-proof-token (ewm-keyboard-capture-begin-module "native-retained-state"))
(setq native-proof-pipe (make-pipe-process :name "native-ewm-events" :noquery t :filter #'native-proof-filter))
(ewm-init-event-channel native-proof-pipe)
(unless (ewm-proof-start-headless) (error "Real in-process EWM failed to start"))
(native-proof-wait (lambda () (memq 'ready native-proof-events)))

(setq native-proof-native-before (ewm-get-debug-state-module))
