;;; GNU/native window-discard regression -*- lexical-binding: t; -*-
(defun discard-buffer-check (value message)
  (unless value (error "window-discard: %s" message)))
(defun discard-buffer-regression ()
  (let* ((w (selected-window))
         (b (generate-new-buffer " discard-target"))
         (other (generate-new-buffer " discard-other"))
         (original (window-buffer w))
         (count 0))
    (unwind-protect
        (progn
          ;; Both named parameters, fourth-element and nested second-element
          ;; matches, promotion, malformed lists, and arbitrary non-nil ALL.
          (dolist (all '(nil t non-nil))
            (dolist (shape '(fourth second both neither short atom dotted))
              (dolist (which '(current previous both))
                (let* ((match (cond ((eq shape 'fourth) (list 'same 'window w b))
                                    ((eq shape 'second) (list 'same (list b 1 2 3) w other))
                                    ((eq shape 'both) (list 'same (list b 1) w b))
                                    ((eq shape 'neither) (list 'same (list other 1) w other))
                                    ((eq shape 'short) (list 'same))
                                    ((eq shape 'atom) 'malformed)
                                    (t (cons 'same 'malformed))))
                       (keep (list 'same (list other 1 2 3) w other))
                       (qr (if (memq which '(current both)) match keep))
                       (qp (if (memq which '(previous both)) match keep))
                       (matching (memq shape '(fourth second both)))
                       (bad (memq shape '(atom dotted)))
                       (expected-prev (if (and all matching (memq which '(previous both))) nil qp))
                       (expected-current (if (and all matching (memq which '(current both))) expected-prev qr))
                       (err nil))
                  (set-window-parameter w 'quit-restore qr)
                  (set-window-parameter w 'quit-restore-prev qp)
                  (set-window-parameter w 'unrelated b)
                  (set-window-prev-buffers w (list (list b 1 1) (list other 1 1)))
                  (set-window-next-buffers w (list b other b))
                  (condition-case e (window-discard-buffer-from-window b w all)
                    (error (setq err (car e))))
                  (discard-buffer-check (eq err (if (and all bad) 'wrong-type-argument nil)) "malformed error/ALL")
                  (unless err
                    (discard-buffer-check (eq (window-parameter w 'quit-restore) expected-current) "current preservation/promotion")
                    (discard-buffer-check (eq (window-parameter w 'quit-restore-prev)
                                              (if (and all matching (memq which '(current both))) nil expected-prev)) "previous preservation/clear"))
                  (discard-buffer-check (eq (window-parameter w 'unrelated) b) "unrelated parameter")
                  (discard-buffer-check (equal (window-prev-buffers w) (list (list other 1 1))) "previous history")
                  (discard-buffer-check (equal (window-next-buffers w) (list other)) "next history")
                  (discard-buffer-check (eq (window-buffer w) original) "no display mutation")
                  (setq count (1+ count))))))
          (princ (format "DISCARD cases=%d PASS\n" count))
          count)
      (set-window-parameter w 'quit-restore nil)
      (set-window-parameter w 'quit-restore-prev nil)
      (set-window-parameter w 'unrelated nil)
      (kill-buffer b)
      (kill-buffer other))))
(discard-buffer-regression)
