;;; neo-term-colors-test.el --- Face palette bridge tests -*- lexical-binding: t -*-
(require 'ert)
(require 'neo-term-colors)
(declare-function neo-term "neo-term" ())
(declare-function neo-term-exec "neo-term"
                  (executable argv directory environment &optional origin))

(defun neo-term-colors-test--rgb (face attribute frame)
  (mapcar (lambda (n) (round n 257))
          (color-values (face-attribute face attribute frame 'default) frame)))

(ert-deftest neo-term-colors-explicit-default-and-sixteen-channel-faces ()
  ;; Real GNU face resolution; batch TTY display is not rendered pixel proof.
  (let* ((frame (selected-frame))
         (palette (neo-term--frame-palette frame)))
    (should (= (length palette) 106))
    (should (equal (append (cl-subseq palette 0 3) nil)
                   (neo-term-colors-test--rgb 'default :foreground frame)))
    (should (equal (append (cl-subseq palette 3 6) nil)
                   (neo-term-colors-test--rgb 'default :background frame)))
    (dotimes (index 16)
      (let ((face (aref ansi-term-color-vector (1+ index))))
        (should (equal (append (cl-subseq palette (+ 9 (* index 3)) (+ 12 (* index 3))) nil)
                       (neo-term-colors-test--rgb face :foreground frame)))
        (should (equal (append (cl-subseq palette (+ 57 (* index 3)) (+ 60 (* index 3))) nil)
                       (neo-term-colors-test--rgb face :background frame)))))))

(ert-deftest neo-term-colors-inherited-and-user-term-override ()
  (let ((frame (selected-frame)))
    (unwind-protect
        (progn
          (set-face-attribute 'ansi-color-red frame :foreground "#123456")
          (set-face-attribute 'term-color-red frame :foreground 'unspecified)
          (should (equal (append (cl-subseq (neo-term--frame-palette frame) 12 15) nil)
                         (neo-term-colors-test--rgb 'term-color-red :foreground frame)))
          (set-face-attribute 'term-color-red frame :foreground "#654321")
          (should-not (equal (neo-term-colors-test--rgb 'term-color-red :foreground frame)
                             (neo-term-colors-test--rgb 'ansi-color-red :foreground frame)))
          (should (equal (append (cl-subseq (neo-term--frame-palette frame) 12 15) nil)
                         (neo-term-colors-test--rgb 'term-color-red :foreground frame))))
      (face-spec-recalc 'ansi-color-red frame)
      (face-spec-recalc 'term-color-red frame))))

(ert-deftest neo-term-colors-independent-background-and-unspecified ()
  (let ((frame (selected-frame)))
    (unwind-protect
        (progn
          (set-face-attribute 'term-color-blue frame :foreground "#ff0000"
                              :background "#00ff00")
          (let ((palette (neo-term--frame-palette frame)))
            (should-not (equal (cl-subseq palette 21 24) (cl-subseq palette 69 72))))
          (set-face-attribute 'term-color-blue frame :foreground 'unspecified
                              :background 'unspecified :inherit nil)
          (let ((palette (neo-term--frame-palette frame)))
            (should (equal (append (cl-subseq palette 21 24) nil)
                           (neo-term-colors-test--rgb 'default :foreground frame)))))
      (face-spec-recalc 'term-color-blue frame))))

(ert-deftest neo-term-colors-bold-option-separate-from-bright-slots ()
  (let ((ansi-color-bold-is-bright nil))
    (let ((normal (neo-term--frame-palette (selected-frame))))
      (should-not (aref normal 105))
      (let ((ansi-color-bold-is-bright t))
        (let ((bright (neo-term--frame-palette (selected-frame))))
          (should (aref bright 105))
          (should (equal (cl-subseq normal 0 105) (cl-subseq bright 0 105))))))))

(ert-deftest neo-term-colors-cache-and-failed-publication ()
  (let ((neo-term--palette-active t)
        (neo-term--palette-cache (make-hash-table :test 'eq))
        (neo-term--palette-timer nil)
        calls fail)
    ;; Mock only transport and graphical admission; faces/colors are real GNU.
    (cl-letf (((symbol-function 'neo-term--palette-frames) (lambda () (frame-list)))
              ((symbol-function 'neomacs-terminal-set-palette)
               (lambda (frame palette)
                 (if fail (error "Injected native queue failure")
                   (push (cons frame palette) calls)))))
      (neo-term--refresh-palettes)
      (neo-term--refresh-palettes)
      (should (= (length calls) (length (frame-list))))
      (clrhash neo-term--palette-cache)
      (setq fail t)
      (should-error (neo-term--refresh-palettes))
      (should (= (hash-table-count neo-term--palette-cache) 0)))))

(ert-deftest neo-term-colors-theme-and-face-change-invalidation ()
  (let ((neo-term--palette-active nil)
        (neo-term--palette-cache (make-hash-table :test 'eq))
        (neo-term--palette-timer nil)
        calls)
    (unwind-protect
        (cl-letf (((symbol-function 'neo-term--palette-frames) (lambda () (frame-list)))
                  ((symbol-function 'neomacs-terminal-set-palette)
                   (lambda (frame palette) (push (cons frame palette) calls))))
          (neo-term--ensure-palettes)
          (let ((initial-count (length calls)))
            (set-face-attribute 'term-color-green (selected-frame) :foreground "#ff0000")
            (should (timerp neo-term--palette-timer))
            (let ((timer neo-term--palette-timer))
              (set-face-attribute 'term-color-green (selected-frame) :foreground "#0000ff")
              (should (eq timer neo-term--palette-timer))
              (sleep-for 0.02))
            (should (> (length calls) initial-count))
            (should-not neo-term--palette-timer)
            (let ((count (length calls)))
              (run-hook-with-args 'enable-theme-functions 'test)
              (should (timerp neo-term--palette-timer))
              (cancel-timer neo-term--palette-timer)
              (neo-term--refresh-palettes)
              (should (= count (length calls))))))
      (when neo-term--palette-timer (cancel-timer neo-term--palette-timer))
      (dolist (setter '(set-face-attribute face-spec-set face-spec-recalc custom-theme-set-faces modify-frame-parameters copy-face))
        (advice-remove setter #'neo-term--schedule-palette-refresh))
      (remove-hook 'enable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'disable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'after-make-frame-functions #'neo-term--refresh-palettes)
      (remove-hook 'delete-frame-functions #'neo-term--retire-frame-palette)
      (dolist (variable '(ansi-color-bold-is-bright ansi-term-color-vector))
        (remove-variable-watcher variable #'neo-term--palette-variable-changed))
      (let ((neo-term--palette-active nil))
        (face-spec-recalc 'term-color-green (selected-frame))))))

(ert-deftest neo-term-colors-cursor-background-with-default-fallback ()
  (let ((frame (selected-frame)))
    (unwind-protect
        (progn
          (set-face-attribute 'cursor frame :background "#ff0000")
          (should (equal (append (cl-subseq (neo-term--frame-palette frame) 6 9) nil)
                         (neo-term-colors-test--rgb 'cursor :background frame)))
          (set-face-attribute 'cursor frame :background 'unspecified :inherit nil)
          (should (equal (append (cl-subseq (neo-term--frame-palette frame) 6 9) nil)
                         (neo-term-colors-test--rgb 'default :foreground frame))))
      (face-spec-recalc 'cursor frame))))

(deftheme neo-term-colors-test-theme "Disposable palette bridge test theme.")
(ert-deftest neo-term-colors-actual-theme-switch-publishes-and-retains-user-priority ()
  (let ((default-fg (face-attribute 'default :foreground (selected-frame)))
        (default-bg (face-attribute 'default :background (selected-frame)))
        (user-spec (copy-tree (get 'term-color-yellow 'theme-face)))
        (neo-term--palette-active nil)
        (neo-term--palette-cache (make-hash-table :test 'eq))
        (neo-term--palette-timer nil)
        calls)
    (unwind-protect
        (cl-letf (((symbol-function 'neo-term--palette-frames) (lambda () (frame-list)))
                  ((symbol-function 'neomacs-terminal-set-palette)
                   (lambda (frame palette) (push (cons frame palette) calls))))
          (neo-term--ensure-palettes)
          (custom-theme-set-faces 'neo-term-colors-test-theme
                                  ;; Batch frames lose unspecified defaults on
                                  ;; theme enable; keep this disposable fixture
                                  ;; explicit, not a production dark fallback.
                                  `(default ((t (:foreground ,default-fg :background ,default-bg))))
                                  '(term-color-yellow ((t (:foreground "#0000ff")))))
          (enable-theme 'neo-term-colors-test-theme)
          (sleep-for 0.02)
          (should (equal (cdr (car calls)) (neo-term--frame-palette (selected-frame))))
          (let ((count (length calls)))
            (custom-theme-set-faces 'user
                                    '(term-color-yellow ((t (:foreground "#ff0000")))))
            (sleep-for 0.02)
            (should (> (length calls) count))
            (disable-theme 'neo-term-colors-test-theme)
            (enable-theme 'neo-term-colors-test-theme)
            (sleep-for 0.02)
            (should (equal (face-attribute 'term-color-yellow :foreground (selected-frame)) "#ff0000"))
            (should (equal (cdr (car calls)) (neo-term--frame-palette (selected-frame))))))
      (when neo-term--palette-timer (cancel-timer neo-term--palette-timer))
      (dolist (setter '(set-face-attribute face-spec-set face-spec-recalc custom-theme-set-faces modify-frame-parameters copy-face))
        (advice-remove setter #'neo-term--schedule-palette-refresh))
      (remove-hook 'enable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'disable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'after-make-frame-functions #'neo-term--refresh-palettes)
      (remove-hook 'delete-frame-functions #'neo-term--retire-frame-palette)
      (dolist (variable '(ansi-color-bold-is-bright ansi-term-color-vector))
        (remove-variable-watcher variable #'neo-term--palette-variable-changed))
      (let ((neo-term--palette-active nil))
        (disable-theme 'neo-term-colors-test-theme)
        (put 'term-color-yellow 'theme-face user-spec)
        (face-spec-recalc 'term-color-yellow (selected-frame))
        (set-face-attribute 'default (selected-frame) :foreground default-fg
                            :background default-bg)))))

(ert-deftest neo-term-colors-palette-callback-cannot-admit-revoked-invocation ()
  (require 'neo-term)
  (let (spawned)
    (cl-letf (((symbol-function 'neomacs-terminal-spawn)
               (lambda (&rest _) (setq spawned t) 41))
              ((symbol-function 'neo-term--ensure-palettes)
               (lambda () (fundamental-mode))))
      (should-error (neo-term-exec "/bin/echo" nil "/" '("SHELL=/bin/sh")))
      (should-not spawned))))

(ert-deftest neo-term-colors-copy-face-invalidates-cached-canonical-slot ()
  (let ((neo-term--palette-active nil)
        (neo-term--palette-cache (make-hash-table :test 'eq))
        (neo-term--palette-timer nil)
        calls)
    (unwind-protect
        (cl-letf (((symbol-function 'neo-term--palette-frames) (lambda () (frame-list)))
                  ((symbol-function 'neomacs-terminal-set-palette)
                   (lambda (frame palette) (push (cons frame palette) calls))))
          (neo-term--ensure-palettes)
          (let ((count (length calls)))
            (copy-face 'default 'term-color-red (selected-frame))
            (should (timerp neo-term--palette-timer))
            (sleep-for 0.02)
            (should (> (length calls) count))
            (should (equal (cdr (car calls)) (neo-term--frame-palette (selected-frame))))))
      (when neo-term--palette-timer (cancel-timer neo-term--palette-timer))
      (dolist (setter '(set-face-attribute face-spec-set face-spec-recalc
                                           custom-theme-set-faces modify-frame-parameters copy-face))
        (advice-remove setter #'neo-term--schedule-palette-refresh))
      (remove-hook 'enable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'disable-theme-functions #'neo-term--schedule-palette-refresh)
      (remove-hook 'after-make-frame-functions #'neo-term--refresh-palettes)
      (remove-hook 'delete-frame-functions #'neo-term--retire-frame-palette)
      (dolist (variable '(ansi-color-bold-is-bright ansi-term-color-vector))
        (remove-variable-watcher variable #'neo-term--palette-variable-changed))
      (let ((neo-term--palette-active nil))
        (face-spec-recalc 'term-color-red (selected-frame))))))

(ert-deftest neo-term-colors-legacy-public-constructor-refuses-revoked-owner ()
  (require 'neo-term)
  (let ((foreign (generate-new-buffer " *palette-foreign*"))
        (initial (current-buffer))
        (neo-term--terminals (make-hash-table :test 'eql))
        created)
    (unwind-protect
        (dolist (revoke '(switch mode))
          (switch-to-buffer initial)
          (cl-letf (((symbol-function 'neomacs-terminal-create)
                     (lambda (&rest _) (setq created t) 41))
                    ((symbol-function 'neo-term--ensure-palettes)
                     (lambda ()
                       (if (eq revoke 'switch) (switch-to-buffer foreign)
                         (fundamental-mode)))))
            (should-error (neo-term))
            (should-not created)
            (should (= (hash-table-count neo-term--terminals) 0))
            (should-not (buffer-local-value 'neo-term--id foreign))))
      (switch-to-buffer initial)
      (when (buffer-live-p foreign) (kill-buffer foreign)))))

(provide 'neo-term-colors-test)
;;; neo-term-colors-test.el ends here
