[package]
name = "neomacs-renderer-wgpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WGPU text renderer primitives for Neomacs"

[features]
default = []
video = ["dep:neomacs-video"]
video-dmabuf = ["video"]
webview = []

[dependencies]
enum_dispatch.workspace = true
rustc-hash.workspace = true
cosmic-text.workspace = true
swash.workspace = true
fontdb.workspace = true
wgpu.workspace = true
wgpu-hal.workspace = true
naga.workspace = true
tracing.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
pollster.workspace = true
ash.workspace = true
image.workspace = true
png.workspace = true
zune-jpeg.workspace = true
imagesize.workspace = true
flate2.workspace = true
libc.workspace = true
resvg.workspace = true
svgtypes.workspace = true
simplecss.workspace = true
neomacs-display-protocol.workspace = true
neomacs-font-materializer.workspace = true
neomacs-layout-engine.workspace = true
neomacs-video = { workspace = true, optional = true }

[dev-dependencies]
neomacs-infra.workspace = true
neomacs-test-fonts.workspace = true
tracing-test.workspace = true
jpeg-encoder.workspace = true
image-extras.workspace = true

[lints]
workspace = true
