[package]
name = "neomacs-display-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared display protocol types for Neomacs layout/render/runtime"

[features]
default = []
neo-term = []

[dependencies]
rustc-hash.workspace = true
bitflags.workspace = true
num_enum.workspace = true
serde.workspace = true
nutype.workspace = true
serde_json = "1"
strum.workspace = true
tracing.workspace = true
crossbeam-channel.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[dev-dependencies]
neomacs-infra.workspace = true
proptest.workspace = true

[lints]
workspace = true
