//! GNU 31.1 oracle pins for P1.1 Stage 2 call shapes. The fixtures are
//! generated by GNU, never from NeoVM. Refresh one isolated test with
//! `UPDATE_EXPECT=1 EMACS=/path/to/emacs cargo nextest run ...`.
//!
//! GNU's `bytecode.c:Bcall` records the original called value and NARGS
//! before `exec_byte_code` pads optionals or builds a rest list. Its frame
//! pins the entered object across redefinition and GC. The tests normalize
//! only byte-code implementation bytes, preserving object identity, arity,
//! every argument and complete error data.

use super::*;

#[cfg(test)]
#[path = "direct_call_shape_edges_test.rs"]
mod edges;
use std::path::PathBuf;

/// Frozen GNU output keeps the ordinary gate independent of an installed
/// GNU binary. Refresh is deliberately explicit and never records NeoVM.
fn gnu_expect(name: &str, program: &str, observe: &str, fixture: &str) -> String {
    if std::env::var("UPDATE_EXPECT").as_deref() != Ok("1") {
        return fixture.trim_end().to_owned();
    }
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let tmp = root.join("../../tmp");
    std::fs::create_dir_all(&tmp).expect("oracle temporary directory");
    let script = tmp.join(format!("direct-shape-{name}-{}.el", std::process::id()));
    std::fs::write(
        &script,
        format!(
            ";;; -*- lexical-binding: t; -*-\n(require 'bytecomp)\n{WARM}\n{program}\n(let ((print-length nil) (print-level nil)) (prin1 {observe}))\n"
        ),
    )
    .expect("write GNU oracle input");
    let emacs = std::env::var_os("EMACS").unwrap_or_else(|| {
        PathBuf::from(std::env::var_os("HOME").expect("HOME"))
            .join(".local/bin/emacs")
            .into_os_string()
    });
    let result = std::process::Command::new(emacs)
        .args(["--batch", "-Q", "-l"])
        .arg(&script)
        .output()
        .expect("run GNU oracle");
    assert!(
        result.status.success(),
        "GNU oracle {name}: {}",
        String::from_utf8_lossy(&result.stderr)
    );
    let output = String::from_utf8(result.stdout).expect("GNU output is UTF-8");
    assert!(!output.is_empty(), "GNU produced an expectation");
    std::fs::write(
        root.join("src/emacs_core/runtime/jit/tests/direct_call_shape_parity")
            .join(format!("{name}.expect")),
        format!("{}\n", output.trim_end()),
    )
    .expect("write GNU fixture");
    output.trim_end().to_owned()
}

/// Each bit is tested independently, alongside the ordinary shim, the
/// exact-only direct path, memory direct calls and the forced-shim
/// fallbacks. Memory calls may decline optional short/rest normalization;
/// register runs retain their engagement assertions and return positions.
/// The harness also checks that evaluator depth and specpdl are restored
/// after observation.
fn assert_gnu_shape(
    name: &str,
    shape: &str,
    program: &'static str,
    observe: &'static str,
    fixture: &str,
    named_hit: bool,
) -> [Run; 4] {
    let knob = DirectShapesKnob::parse(Some(shape));
    let expected = gnu_expect(name, program, observe, fixture);
    let modes = [
        (Mode::Shim, DirectShapesKnob::OFF),
        (Mode::Direct, DirectShapesKnob::OFF),
        (Mode::Direct, knob),
        (Mode::DirectForcedSlow, knob),
    ];
    let runs = modes.map(|(mode, shapes)| run_in_with(mode, shapes, program, observe));
    for (run, (mode, shapes)) in runs.iter().zip(modes) {
        assert_eq!(run.out, expected, "GNU {name}: {mode:?}, {shapes:?}");
    }
    assert!(
        runs[2].direct_sites > runs[1].direct_sites,
        "{shape} independently emits direct sites: {runs:?}"
    );
    if named_hit {
        assert!(
            runs[2].shim_calls < runs[1].shim_calls,
            "{shape} independently bypasses the named-call shim: {runs:?}"
        );
    }
    for mode in [Mode::DirectMemory, Mode::DirectMemoryForcedSlow] {
        let run = run_in_with(mode, knob, program, observe);
        assert_eq!(run.out, expected, "GNU {name}: {mode:?}, {knob:?}");
    }
    runs
}

const FRAME_PROGRAM: &str = r#"(progn
  (require 'cl-lib)
  (defvar neovm--sp-target nil)
  (defun neovm--sp-normalize (f)
    (if (byte-code-function-p f)
        (list 'byte-code-function (func-arity f) (eq f neovm--sp-target)) f))
  (defun neovm--sp-show ()
    (let (mapped frames)
      (mapbacktrace
       (lambda (evald f args flags)
         (when (eq f neovm--sp-target)
           (push (list evald (neovm--sp-normalize f) args flags) mapped)))
       'neovm--sp-show)
      (dolist (frame (backtrace-frames 'neovm--sp-show))
        (when (eq (cadr frame) neovm--sp-target)
          (push (cons (car frame)
                      (cons (neovm--sp-normalize (cadr frame)) (cddr frame))) frames)))
      (let ((one (backtrace-frame 1 'neovm--sp-show)))
        (list (nreverse mapped)
              (cons (car one) (cons (neovm--sp-normalize (cadr one)) (cddr one)))
              (nreverse frames)))))
  (defun neovm--sp-opt (a &optional b c)
    (if (eq a 'show) (neovm--sp-show) (list a b c)))
  (defun neovm--sp-opt-caller (a) (neovm--sp-opt a))
  (defun neovm--sp-rest (a &optional b &rest tail)
    (if (eq a 'show) (neovm--sp-show) (list a b tail)))
  (defun neovm--sp-rest-caller (a) (neovm--sp-rest a 1 2 3))
  (defun neovm--sp-constant-caller (a)
    (cl-flet ((local (x) (if (eq x 'show) (neovm--sp-show) (list x 2))))
      (list (local a) (local a))))
  (dolist (f '(neovm--sp-normalize neovm--sp-show neovm--sp-opt
               neovm--sp-opt-caller neovm--sp-rest neovm--sp-rest-caller
               neovm--sp-constant-caller)) (byte-compile f))
  (dotimes (i neovm--dc-warm)
    (neovm--sp-opt-caller i) (neovm--sp-rest-caller i)
    (neovm--sp-constant-caller i)))"#;

#[test]
fn gnu_optional_frames_keep_the_called_symbol_and_short_args() {
    assert_gnu_shape(
        "optional-frames",
        "optional",
        FRAME_PROGRAM,
        r#"(progn (setq neovm--sp-target 'neovm--sp-opt)
          (list (neovm--sp-opt-caller 7) (neovm--sp-opt-caller 'show)))"#,
        include_str!("direct_call_shape_parity/optional-frames.expect"),
        true,
    );
}

#[test]
fn gnu_rest_frames_keep_the_call_args_before_marshalling() {
    assert_gnu_shape(
        "rest-frames",
        "rest",
        FRAME_PROGRAM,
        r#"(progn (setq neovm--sp-target 'neovm--sp-rest)
          (list (neovm--sp-rest-caller 7) (neovm--sp-rest-caller 'show)))"#,
        include_str!("direct_call_shape_parity/rest-frames.expect"),
        true,
    );
}

#[test]
fn gnu_constant_frames_keep_the_actual_called_bytecode_object() {
    assert_gnu_shape(
        "constant-frames",
        "constant",
        FRAME_PROGRAM,
        r#"(progn
          (dolist (c (append (aref (symbol-function 'neovm--sp-constant-caller) 2) nil))
            (when (byte-code-function-p c) (setq neovm--sp-target c)))
          (list (byte-code-function-p neovm--sp-target)
                (neovm--sp-constant-caller 7) (neovm--sp-constant-caller 'show)))"#,
        include_str!("direct_call_shape_parity/constant-frames.expect"),
        false,
    );
}

const ARITY_PROGRAM: &str = r#"(progn
  (defun neovm--sa-opt (a &optional b) (if b (+ a b) (* a 2)))
  (defun neovm--sa-opt-caller (a) (neovm--sa-opt a))
  (defun neovm--sa-rest (a &rest tail) (list a tail))
  (defun neovm--sa-rest-caller (a) (neovm--sa-rest a 1))
  (dolist (f '(neovm--sa-opt neovm--sa-opt-caller neovm--sa-rest
               neovm--sa-rest-caller)) (byte-compile f))
  (dotimes (i neovm--dc-warm) (neovm--sa-opt-caller i) (neovm--sa-rest-caller i)))"#;

#[test]
fn gnu_optional_redefinition_keeps_complete_wrong_arity_data() {
    assert_gnu_shape(
        "optional-arity",
        "optional",
        ARITY_PROGRAM,
        r#"(let ((old (symbol-function 'neovm--sa-opt)))
          (list (neovm--sa-opt-caller 4)
                (progn (fset 'neovm--sa-opt (byte-compile (lambda (a b) (list a b))))
                       (condition-case err (neovm--sa-opt-caller 5) (error err)))
                (progn (fset 'neovm--sa-opt old) (neovm--sa-opt-caller 6))))"#,
        include_str!("direct_call_shape_parity/optional-arity.expect"),
        true,
    );
}

#[test]
fn gnu_rest_redefinition_keeps_complete_wrong_arity_data() {
    assert_gnu_shape(
        "rest-arity",
        "rest",
        ARITY_PROGRAM,
        r#"(let ((old (symbol-function 'neovm--sa-rest)))
          (list (neovm--sa-rest-caller 4)
                (progn (fset 'neovm--sa-rest
                             (byte-compile (lambda (a b c &rest tail) (list a b c tail))))
                       (condition-case err (neovm--sa-rest-caller 5) (error err)))
                (progn (fset 'neovm--sa-rest old) (neovm--sa-rest-caller 6))))"#,
        include_str!("direct_call_shape_parity/rest-arity.expect"),
        true,
    );
}

#[test]
fn gnu_constant_calls_keep_complete_wrong_arity_data() {
    const PROGRAM: &str = r#"(progn
      (require 'cl-lib)
      (defun neovm--sa-constant-caller (n)
        (cl-flet ((local (x) (if (> x 0) (list x 2) nil)))
          (cond ((> n 0) (local n)) ((= n 0) (local)) (t (local n 1)))))
      (byte-compile 'neovm--sa-constant-caller)
      (dotimes (i neovm--dc-warm) (neovm--sa-constant-caller (1+ i))))"#;
    assert_gnu_shape(
        "constant-arity",
        "constant",
        PROGRAM,
        r#"(list (neovm--sa-constant-caller 4)
          (condition-case err (neovm--sa-constant-caller 0) (error err))
          (condition-case err (neovm--sa-constant-caller -1) (error err))
          (neovm--sa-constant-caller 6))"#,
        include_str!("direct_call_shape_parity/constant-arity.expect"),
        false,
    );
}

const DEBUG_PROGRAM: &str = r#"(progn
  (require 'cl-lib)
  (defvar neovm--sd-arm nil)
  (defvar neovm--sd-log nil)
  (defun neovm--sd-opt (x &optional y) (if y (+ x y) (* x 3)))
  (defun neovm--sd-rest (x &rest tail) (if tail (+ x (car tail)) (* x 3)))
  (defun neovm--sd-opt-caller (x)
    (when neovm--sd-arm (setq debug-on-next-call t)) (neovm--sd-opt x))
  (defun neovm--sd-rest-caller (x)
    (when neovm--sd-arm (setq debug-on-next-call t)) (neovm--sd-rest x 1 2))
  (defun neovm--sd-constant-caller (x)
    (cl-flet ((local (y) (if (> y 0) (* y 3) 0)))
      (when neovm--sd-arm (setq debug-on-next-call t))
      (list (local x) (local x))))
  (dolist (f '(neovm--sd-opt neovm--sd-rest neovm--sd-opt-caller
               neovm--sd-rest-caller neovm--sd-constant-caller)) (byte-compile f))
  (dotimes (i neovm--dc-warm)
    (neovm--sd-opt-caller i) (neovm--sd-rest-caller i) (neovm--sd-constant-caller i)))"#;

macro_rules! debugger_observation {
    ($caller:literal) => {
        concat!(
            r#"(let ((debugger (lambda (&rest args)
                           (push (car args) neovm--sd-log)
                           (if (eq (car args) 'exit) (cadr args) nil)))
                    (neovm--sd-arm t))
              (list ("#,
            $caller,
            r#" 5) (reverse neovm--sd-log) debug-on-next-call))"#
        )
    };
}

#[test]
fn gnu_optional_short_call_obeys_debug_on_next_call() {
    assert_gnu_shape(
        "optional-debug",
        "optional",
        DEBUG_PROGRAM,
        debugger_observation!("neovm--sd-opt-caller"),
        include_str!("direct_call_shape_parity/optional-debug.expect"),
        false,
    );
}

#[test]
fn gnu_rest_call_obeys_debug_on_next_call() {
    assert_gnu_shape(
        "rest-debug",
        "rest",
        DEBUG_PROGRAM,
        debugger_observation!("neovm--sd-rest-caller"),
        include_str!("direct_call_shape_parity/rest-debug.expect"),
        false,
    );
}

#[test]
fn gnu_constant_call_obeys_debug_on_next_call() {
    assert_gnu_shape(
        "constant-debug",
        "constant",
        DEBUG_PROGRAM,
        debugger_observation!("neovm--sd-constant-caller"),
        include_str!("direct_call_shape_parity/constant-debug.expect"),
        false,
    );
}

const DEPTH_PROGRAM: &str = r#"(progn
  (require 'cl-lib)
  (defvar neovm--sl-count 0)
  (defun neovm--sl-opt (n &optional unused)
    (setq neovm--sl-count (1+ neovm--sl-count))
    (if (= n 0) 0 (1+ (neovm--sl-opt (1- n)))))
  (defun neovm--sl-rest (n &rest unused)
    (setq neovm--sl-count (1+ neovm--sl-count))
    (if (= n 0) 0 (1+ (neovm--sl-rest (1- n) n))))
  (defun neovm--sl-constant (n)
    (cl-flet ((local (x)
               (setq neovm--sl-count (1+ neovm--sl-count))
               (if (= x 0) 0 (1+ (neovm--sl-constant (1- x))))))
      (prog1 (local n) (local 0))))
  (dolist (f '(neovm--sl-opt neovm--sl-rest neovm--sl-constant)) (byte-compile f))
  (dotimes (_ 60) (neovm--sl-opt 60) (neovm--sl-rest 60) (neovm--sl-constant 60)))"#;

macro_rules! depth_observation {
    ($callee:literal) => {
        concat!(
            r#"(list (let ((max-lisp-eval-depth 300))
                (setq neovm--sl-count 0)
                (list (condition-case err ("#,
            $callee,
            r#" 1000) (error err))
                      (> neovm--sl-count 100) (< neovm--sl-count 300)))
                  ("#,
            $callee,
            r#" 20))"#
        )
    };
}

#[test]
fn gnu_optional_direct_recursion_obeys_depth_and_recovers() {
    assert_gnu_shape(
        "optional-depth",
        "optional",
        DEPTH_PROGRAM,
        depth_observation!("neovm--sl-opt"),
        include_str!("direct_call_shape_parity/optional-depth.expect"),
        true,
    );
}

#[test]
fn gnu_rest_direct_recursion_obeys_depth_and_recovers() {
    assert_gnu_shape(
        "rest-depth",
        "rest",
        DEPTH_PROGRAM,
        depth_observation!("neovm--sl-rest"),
        include_str!("direct_call_shape_parity/rest-depth.expect"),
        true,
    );
}

#[test]
fn gnu_constant_direct_recursion_obeys_depth_and_recovers() {
    assert_gnu_shape(
        "constant-depth",
        "constant",
        DEPTH_PROGRAM,
        depth_observation!("neovm--sl-constant"),
        include_str!("direct_call_shape_parity/constant-depth.expect"),
        false,
    );
}

const REDEFINE_PROGRAM: &str = r#"(progn
  (require 'cl-lib)
  (defvar neovm--sx-arm nil)
  (defvar neovm--sx-live nil)
  (defvar neovm--sx-keys (make-hash-table :test 'eq :weakness 'key))
  (defun neovm--sx-opt (n x &optional unused)
    (if (= n 0)
        (if neovm--sx-arm
            (progn (fset 'neovm--sx-opt (lambda (&rest _) 'new))
                   (garbage-collect)
                   (setq neovm--sx-live (hash-table-count neovm--sx-keys))
                   (+ (car x) 0.5)) 0)
      (1+ (neovm--sx-opt (1- n) x))))
  (defun neovm--sx-opt-caller (n x) (neovm--sx-opt n x))
  (defun neovm--sx-rest (n &rest x)
    (if (= n 0)
        (if neovm--sx-arm
            (progn (fset 'neovm--sx-rest (lambda (&rest _) 'new))
                   (garbage-collect)
                   (setq neovm--sx-live (hash-table-count neovm--sx-keys))
                   (+ (car x) 0.5)) 0)
      (1+ (neovm--sx-rest (1- n) (car x)))))
  (defun neovm--sx-rest-caller (n x) (neovm--sx-rest n x))
  (defun neovm--sx-constant-caller (x)
    (cl-flet ((local (y)
               (if neovm--sx-arm
                   (progn (fset 'neovm--sx-constant-caller (lambda (_) 'new))
                          (garbage-collect)
                          (setq neovm--sx-live (hash-table-count neovm--sx-keys))
                          (+ (car y) 0.5)) 0)))
      (list (1+ (local x)) (1+ (local x)))))
  (dolist (f '(neovm--sx-opt neovm--sx-opt-caller neovm--sx-rest
               neovm--sx-rest-caller neovm--sx-constant-caller)) (byte-compile f))
  (dotimes (i neovm--dc-warm)
    (neovm--sx-opt-caller 3 '(1)) (neovm--sx-rest-caller 3 1)
    (neovm--sx-constant-caller '(1))))"#;

#[test]
fn gnu_optional_redefinition_and_gc_resume_the_entered_old_object() {
    let runs = assert_gnu_shape(
        "optional-redefine",
        "optional",
        REDEFINE_PROGRAM,
        r#"(progn (puthash (symbol-function 'neovm--sx-opt) t neovm--sx-keys)
          (list (let ((neovm--sx-arm t)) (neovm--sx-opt-caller 3 '(40)))
                neovm--sx-live (neovm--sx-opt-caller 3 '(1))))"#,
        include_str!("direct_call_shape_parity/optional-redefine.expect"),
        true,
    );
    assert!(runs[2].cold_exits > 0, "old optional activation deopts");
}

#[test]
fn gnu_rest_redefinition_and_gc_resume_the_entered_old_object() {
    let runs = assert_gnu_shape(
        "rest-redefine",
        "rest",
        REDEFINE_PROGRAM,
        r#"(progn (puthash (symbol-function 'neovm--sx-rest) t neovm--sx-keys)
          (list (let ((neovm--sx-arm t)) (neovm--sx-rest-caller 3 40))
                neovm--sx-live (neovm--sx-rest-caller 3 1)))"#,
        include_str!("direct_call_shape_parity/rest-redefine.expect"),
        true,
    );
    assert!(runs[2].cold_exits > 0, "old rest activation deopts");
}

#[test]
fn gnu_constant_redefinition_and_gc_resume_the_entered_old_object() {
    let runs = assert_gnu_shape(
        "constant-redefine",
        "constant",
        REDEFINE_PROGRAM,
        r#"(progn
          (dolist (c (append (aref (symbol-function 'neovm--sx-constant-caller) 2) nil))
            (when (byte-code-function-p c) (puthash c t neovm--sx-keys)))
          (list (let ((neovm--sx-arm t)) (neovm--sx-constant-caller '(40)))
                neovm--sx-live (neovm--sx-constant-caller '(1))))"#,
        include_str!("direct_call_shape_parity/constant-redefine.expect"),
        false,
    );
    assert!(runs[2].cold_exits > 0, "old constant activation deopts");
}
